<?php $this->titleBlock("Danh sách lớp - " . Khcn_Api::_()->getItem('default_he_cao_hoc', $this->item->he_cao_hoc)->getTitle());?>
<div class="content-announcements">
<div class="detail">
<div class="title">
<?php echo $this->item->getTitle()?>
</div>
<hr color="#06C"/>
<div class="content">
<!-- Begin content news -->
<?php echo $this->item->getDescription()?>
<!-- End content news -->
</div>
</div>
<br/>
<!-- AddThis Button BEGIN -->
<div class="addthis_toolbox addthis_default_style ">
<a class="addthis_button_preferred_1"></a>
<a class="addthis_button_preferred_2"></a>
<a class="addthis_button_preferred_3"></a>
<a class="addthis_button_preferred_4"></a>
<a class="addthis_button_compact"></a>
<a class="addthis_counter addthis_bubble_style"></a>
</div>
<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4ef0b8c73a846dab"></script>
<!-- AddThis Button END -->
</div>