<div class="art-block">
<div class="art-block-tl"></div>
<div class="art-block-tr"></div>
<div class="art-block-bl"></div>
<div class="art-block-br"></div>
<div class="art-block-tc"></div>
<div class="art-block-bc"></div>
<div class="art-block-cl"></div>
<div class="art-block-cr"></div>
<div class="art-block-cc"></div>
<div class="art-block-body">

<div class="art-blockheader">
<div class="l"></div>
<div class="r"></div>
<div class="t"><span id="" class="Head">Liên
hệ</span></div>
</div>

<div align="right"></div>
<div class="art-blockcontent">
<div class="art-blockcontent-tl"></div>
<div class="art-blockcontent-tr"></div>
<div class="art-blockcontent-bl"></div>
<div class="art-blockcontent-br"></div>
<div class="art-blockcontent-tc"></div>
<div class="art-blockcontent-bc"></div>
<div class="art-blockcontent-cl"></div>
<div class="art-blockcontent-cr"></div>
<div class="art-blockcontent-cc"></div>
<div class="art-blockcontent-body"><!-- block-content -->

<div id="dnn_ctr610_ContentPane"><!-- Start_Module_610 -->
<table id="" class="ModDNNHTMLC" cellpadding="0"
	cellspacing="0" border="0" width="100%">
	<tr>
		<td>
		<div id="" class="Normal">
		<p><strong>Địa chỉ : </strong> Trường Đại học Sài Gòn, 273 An Dương Vương, Phường 3, Quận 5, TP.HCM - Phòng C011</p>
		<p><strong>Điện thoại : </strong> (08) 8.354.271</p> 
		<p><strong>Email : </strong><a href=""> p_khcn@sgu.edu.vn</a></p>
		</div>

		</td>
	</tr>
</table>
<!-- End_Module_610 --></div>

<!-- /block-content -->

<div class="cleared"></div>
</div>
</div>

<div align="right"></div>

<div class="cleared"></div>
</div>
</div>