<div class="navbar-wrapper_footer" id="footer">
        
	<div class="headerBlue footerBlue">
		<?php echo $this->partial('includes/nav.phtml', array('displaySubMenu' => false));?>
	</div>
			
	<div class="container fixtopft">
		<!-- /.navbar -->
		<div class="row fixtop ">
			<div class="span6 fixL fixpdr15">
				<div class="fixpdbt12 fixpdt10">
					<a href="index.html">
						<img src="http://tintuconline.com.vn/images/logottol.png" alt="tintuconline"></a>
				</div>
				<p>
					Trang thông tin điện tử tổng hợp của Công ty Cổ phần Truyền thông VietNamNet</p>
				<p>
					Địa chỉ: Tòa nhà C' land, số 156 ngõ Xã Đàn 2, Đống đa, Hà Nội
				</p>
				<p>
					Điện thoại: (04) 37 722 729 (máy lẻ 1991) - Fax: (04) 37 722 729
				</p>
				<p>
					Email:<a class="cl" rel="nofollow" href="mailto:tintuconline@vietnamnet.vn"> tintuconline@vietnamnet.vn</a>
				</p>
				<p>
					Giấy phép hoạt động số 119/GP-TTĐT, Ngày 09/01/2013 do SỞ THÔNG TIN VÀ TRUYỀN THÔNG
					THÀNH PHỐ HÀ NỘI</p>
			</div>
			<div class="span535 fixL fixpdr10">
				<div class="fixpdbt10">
					<a href="http://vietnamnet.vn/">
						<img src="http://tintuconline.com.vn/images/logovietnamnet.png"></a>
				</div>
				<p>
					Đơn vị quảng cáo: Công ty Cổ phần Truyền thông VietNamNet
				</p>
				<p>
					- Hà Nội. Tel: 04 3772 7988 - Hotline: 0919 405 885
				</p>
				<p>
					Email:<a class="cl" rel="nofollow" href="mailto:vietnamnetjsc.hn@vietnamnet.vn">vietnamnetjsc.hn@vietnamnet.vn</a>
				</p>
				<p>
					Tp.HCM. Tel: 08 3930 9885 - Hotline: 0919 435 885
					</p><p>
						Email:<a class="cl" rel="nofollow" href="mailto:vietnamnetjsc.hcm@vietnamnet.vn">vietnamnetjsc.hcm@vietnamnet.vn</a>
					</p>
					<p>
						Google+</p>
			</div>
			<div class="span150 fixL fixpdTop50">
				<div>
					<a href="http://vads.vn/">
						<img src="http://tintuconline.com.vn/images/lienhequangcao.png">
					</a>
				</div>
			</div>
		</div>
	</div>

</div>