<div class="navbar-wrapper_footer" id="footer">
        
<div class="headerBlue footerBlue" id="AdvCateBottomBanner1">
    <div class="container">
        <div class="navbar navbar-inverse">
            <div class="navbar-inner">
                <div class="nav-collapse collapse">
                    <ul class="nav fnav">
                        <li class="iconhome"><a href="index.html">
                            <img src="http://tintuconline.com.vn/images/icHome.png"></a></li>
                        <li><a href="http://tintuconline.com.vn/thoi-su/p0c1001.vnn" title="Thời sự" class="ts1001">THỜI SỰ</a>                        
                        </li>
                        <li><a href="http://tintuconline.com.vn/the-gioi/p0c1051.vnn" title="Thế giới" class="tg1051">THẾ GIỚI</a>
                        </li>
                        <li><a href="http://tintuconline.com.vn/giai-tri/p0c1086.vnn" title="Giải trí" class="gt1086">GIẢI TRÍ</a>
                        </li>
                        <li><a href="http://tintuconline.com.vn/doi-song/p0c1087.vnn" class="ds1087">ĐỜI SỐNG</a></li>
                        <li><a href="http://tintuconline.com.vn/giao-duc/p0c1092.vnn" class="gd1092">GIÁO DỤC</a></li>
                        <li><a href="http://tintuconline.com.vn/kinh-doanh/p0c1034.vnn" class="kd1034">KINH DOANH</a></li>
                        <li><a href="http://tintuconline.com.vn/video/p0c1085.vnn" class="vd1085">VIDEO</a></li>
                        <li><a href="http://tintuconline.com.vn/photo/p0c1084.vnn" class="pt1084">PHOTO</a></li>
                        <li><a href="http://tintuconline.com.vn/the-thao/p0c1047.vnn" class="tt1047">THỂ THAO</a></li>
                        <li><a href="http://tintuconline.com.vn/cong-nghe/p0c1056.vnn" class="cn1056">CÔNG NGHỆ</a></li>
                        <li><a href="http://tintuconline.com.vn/phap-luat/p0c1002.vnn" class="pl1002">PHÁP LUẬT</a></li>
                        <li><a href="http://tintuconline.com.vn/v-quiz/p0c1160.vnn" class="vq1160">V-QUIZ</a></li>
                    </ul>
                </div>
                <!--/.nav-collapse -->
            </div>
            <!-- /.navbar-inner -->
        </div>
        <!-- /.navbar -->
    </div>
</div>

        
<div class="container fixtopft">
    <!-- /.navbar -->
    <div class="row fixtop ">
        <div class="span6 fixL fixpdr15">
            <div class="fixpdbt12 fixpdt10">
                <a href="index.html">
                    <img src="http://tintuconline.com.vn/images/logottol.png" alt="tintuconline"></a>
            </div>
            <p>
                Trang thông tin điện tử tổng hợp của Công ty Cổ phần Truyền thông VietNamNet</p>
            <p>
                Địa chỉ: Tòa nhà C' land, số 156 ngõ Xã Đàn 2, Đống đa, Hà Nội
            </p>
            <p>
                Điện thoại: (04) 37 722 729 (máy lẻ 1991) - Fax: (04) 37 722 729
            </p>
            <p>
                Email:<a class="cl" rel="nofollow" href="mailto:tintuconline@vietnamnet.vn"> tintuconline@vietnamnet.vn</a>
            </p>
            <p>
                Giấy phép hoạt động số 119/GP-TTĐT, Ngày 09/01/2013 do SỞ THÔNG TIN VÀ TRUYỀN THÔNG
                THÀNH PHỐ HÀ NỘI</p>
        </div>
        <div class="span535 fixL fixpdr10">
            <div class="fixpdbt10">
                <a href="http://vietnamnet.vn/">
                    <img src="http://tintuconline.com.vn/images/logovietnamnet.png"></a>
            </div>
            <p>
                Đơn vị quảng cáo: Công ty Cổ phần Truyền thông VietNamNet
            </p>
            <p>
                - Hà Nội. Tel: 04 3772 7988 - Hotline: 0919 405 885
            </p>
            <p>
                Email:<a class="cl" rel="nofollow" href="mailto:vietnamnetjsc.hn@vietnamnet.vn">vietnamnetjsc.hn@vietnamnet.vn</a>
            </p>
            <p>
                Tp.HCM. Tel: 08 3930 9885 - Hotline: 0919 435 885
                </p><p>
                    Email:<a class="cl" rel="nofollow" href="mailto:vietnamnetjsc.hcm@vietnamnet.vn">vietnamnetjsc.hcm@vietnamnet.vn</a>
                </p>
                <p>
                    Google+</p>
        </div>
        <div class="span150 fixL fixpdTop50">
            <div>
                <a href="http://vads.vn/">
                    <img src="http://tintuconline.com.vn/images/lienhequangcao.png">
                </a>
            </div>
        </div>
    </div>
</div>

    </div>