<form method="post" action="http://tintuconline.com.vn/" id="from1" onsubmit="return false;">
<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="/wEPDwUKMTA5NTU1MTQ2OGRk">
<div class="navbar-wrapper">
        
<div class="container">
    <div class="row">
        <div class="span3 fixspan3">
            <a href="index.html" title="Tin tức online">
                <img src="<?php echo $this->baseUrl() . '/images/logo.jpg'?>" alt="Tin tức online"></a>
        </div>
        <div class="span760 fixleft contact">
            <!-- <img src="images/contact.png" /><img src="images/contact.png" /> -->
            <div class="span6">
            </div>
            <div class="span4 fixpdTop5">
                <div class="span1 fixpdr10">
                </div>
                
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Tìm kiếm" name="keyword" id="keyword" style="margin-bottom: 0" onfocus="if(this.value=='Từ khoá') this.value='';">
                    <div class="input-group-btn ">
                        <button class="btn btn-default" type="button" onclick="search()">
                            <img src="http://tintuconline.com.vn/images/search_1.png">
                        </button>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">

    function search() {
        var key = $('#keyword').val();
        if (key != "" && key != "Tìm kiếm")
            location.href = "/Pages/Search.aspx?Keyword=" + encodeURIComponent($('#keyword').val());
        else 
            alert("Bạn chưa nhập từ khóa!");
        return false;
    }

    $('#keyword').keypress(function (event) {
        if (event.which == 13) {
            event.preventDefault();
            search();
        }
    });
</script>
<!-- Begin nav -->
<?php echo $this->render('includes/nav.phtml') ?>
<!-- End nav -->
</div></form>