<form method="post" action="http://tintuconline.com.vn/" id="from1" onsubmit="return false;">
<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="/wEPDwUKMTA5NTU1MTQ2OGRk">

    <div class="navbar-wrapper">
        
<div class="container">
    <div class="row">
        <div class="span3 fixspan3">
            <a href="index.html" title="Tin tức online">
                <img src="http://tintuconline.com.vn/images/logottol2x.png" alt="Tin tức online"></a>
        </div>
        <div class="span760 fixleft contact">
            <!-- <img src="images/contact.png" /><img src="images/contact.png" /> -->
            <div class="span6">
                <ul class="nav00">
                    <li><span>Hotline: </span><a rel="nofollow" href="mailto:tintuconline@vietnamnet.vn">
                        tintuconline@vietnamnet.vn</a></li>
                     <li><a>Đặt TTOL làm trang chủ </a></li>
                </ul>
            </div>
            <div class="span4 fixpdTop5">
                <div class="span1 fixpdr10">
                    <a>
                        <img src="http://tintuconline.com.vn/images/logovnn.png"></a>
                </div>
                
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Tìm kiếm" name="keyword" id="keyword" style="margin-bottom: 0" onfocus="if(this.value=='Từ khoá') this.value='';">
                    <div class="input-group-btn ">
                        <button class="btn btn-default" type="button" onclick="search()">
                            <img src="http://tintuconline.com.vn/images/search_1.png">
                        </button>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">

    function search() {
        var key = $('#keyword').val();
        if (key != "" && key != "Tìm kiếm")
            location.href = "/Pages/Search.aspx?Keyword=" + encodeURIComponent($('#keyword').val());
        else 
            alert("Bạn chưa nhập từ khóa!");
        return false;
    }

    $('#keyword').keypress(function (event) {
        if (event.which == 13) {
            event.preventDefault();
            search();
        }
    });
</script>

        
<div class="headerBlue">
    <div class="container">
        <div class="navbar navbar-inverse">
            <div class="navbar-inner">
                <div class="nav-collapse collapse">
                    <ul class="nav">
                        <li class="iconhome activenav"><a href="index.html">
                            <img src="http://tintuconline.com.vn/images/icHome.png"></a></li>
                        <li class=""><a href="http://tintuconline.com.vn/thoi-su/p0c1001.vnn" title="Thời sự" class="ts1001">THỜI SỰ</a>
                            <ul style="display: none;">
                                

                            </ul>
                        </li>
                        <li class=""><a href="http://tintuconline.com.vn/diem-nhin/p0c1159.vnn" title="Điểm nhìn" class="dn1159">ĐIỂM NHÌN</a>
                            <ul style="display: none;">
                                

                            </ul>
                        </li>
                        <li class=""><a href="http://tintuconline.com.vn/kinh-doanh/p0c1034.vnn" class="kd1034">KINH DOANH</a>
                            <ul style="display: none;">
                                <li><a href="http://tintuconline.com.vn/thi-truong/p1034c1094.vnn" title="Thị trường">Thị trường</a></li><li><a href="http://tintuconline.com.vn/doanh-nghiep/p1034c1037.vnn" title="Doanh nghiệp">Doanh nghiệp</a></li><li><a href="http://tintuconline.com.vn/khoi-nghiep/p1034c1038.vnn" title="Khởi nghiệp">Khởi nghiệp</a></li>

                            </ul>
                        </li>
                        <li class=""><a href="http://tintuconline.com.vn/giao-duc/p0c1092.vnn" class="gd1092">GIÁO DỤC</a>
                            <ul style="display: none;">
                                <li><a href="http://tintuconline.com.vn/gia-tri/p1092c1162.vnn" title="Giá trị">Giá trị</a></li><li><a href="http://tintuconline.com.vn/ky-nang/p1092c1163.vnn" title="Kỹ năng">Kỹ năng</a></li><li><a href="http://tintuconline.com.vn/du-hoc/p1092c1164.vnn" title="Du học">Du học</a></li>

                            </ul>
                        </li>
                        <li class=""><a href="http://tintuconline.com.vn/doi-song/p0c1087.vnn" class="ds1087">ĐỜI SỐNG</a>
                            <ul style="display: none;">
                                <li><a href="http://tintuconline.com.vn/gia-dinh/p1087c1073.vnn" title="Gia đình">Gia đình</a></li><li><a href="http://tintuconline.com.vn/tinh-yeu/p1087c1071.vnn" title="Tình yêu">Tình yêu</a></li><li><a href="http://tintuconline.com.vn/nhip-song-tre/p1087c1074.vnn" title="Nhịp sống trẻ">Nhịp sống trẻ</a></li><li><a href="http://tintuconline.com.vn/cong-so/p1087c1072.vnn" title="Công sở">Công sở</a></li>

                                <li><a href="http://tintuconline.com.vn/song-khoe/p0c1069.vnn" title="Sống khỏe">Sống khỏe</a></li>
                                <li><a href="http://tintuconline.com.vn/di-an-choi/p0c1078.vnn" title="Đi Ăn Chơi">Đi ăn chơi</a></li>
                                <li><a href="http://tintuconline.com.vn/lam-dep/p0c1068.vnn" title="Làm đẹp">Làm đẹp</a></li>
                            </ul>
                        </li>
                        <li class=""><a href="http://tintuconline.com.vn/giai-tri/p0c1086.vnn" title="Giải trí" class="gt1086">GIẢI TRÍ</a>
                            <ul style="display: none;">
                                <li class=""><a href="http://tintuconline.com.vn/showbiz/p1086c1044.vnn" title="Showbiz">Showbiz</a></li><li><a href="http://tintuconline.com.vn/thoi-trang/p1086c1067.vnn" title="Thời trang">Thời trang</a></li><li><a href="http://tintuconline.com.vn/dien-anh/p1086c1046.vnn" title="Điện ảnh">Điện ảnh</a></li><li><a href="http://tintuconline.com.vn/am-nhac/p1086c1045.vnn" title="Âm nhạc">Âm nhạc</a></li>

                                <li><a href="http://tintuconline.com.vn/hot-face/p0c1158.vnn" title="Hot Face">HOT FACE</a></li>
                            </ul>
                        </li>
                        <li class=""><a href="http://tintuconline.com.vn/buon-chuyen/p0c1079.vnn" title="Buôn chuyện" class="bc1079">BUÔN CHUYỆN</a>
                            <ul style="display: none;">
                                

                            </ul>
                        </li>
                        <li class=""><a href="http://tintuconline.com.vn/photo/p0c1084.vnn" class="pt1084">PHOTO</a></li>
                        <li><a href="http://tintuconline.com.vn/video/p0c1085.vnn" class="vd1085">VIDEO</a></li>
                        <li class=""><a href="http://tintuconline.com.vn/the-gioi/p0c1051.vnn" title="Thế giới" class="tg1051">THẾ GIỚI</a>
                            <ul style="display: none;">
                                <li><a href="http://tintuconline.com.vn/tin-tuc/p1051c1054.vnn" title="Tin tức">Tin tức</a></li><li><a href="http://tintuconline.com.vn/xfile/p1051c1053.vnn" title="X-File">X-File</a></li><li><a href="http://tintuconline.com.vn/chuyen-4-phuong/p1051c1052.vnn" title="Chuyện 4 phương">Chuyện 4 phương</a></li>

                            </ul>
                        </li>
                        <li class=""><a href="http://tintuconline.com.vn/cong-nghe/p0c1056.vnn" class="cn1056">CÔNG NGHỆ</a>
                            <ul style="display: none;">
                                

                            </ul>
                        </li>
                        <li class=""><a href="http://tintuconline.com.vn/phap-luat/p0c1002.vnn" class="pl1002">PHÁP LUẬT</a>
                            <ul style="display: none;">
                                

                            </ul>
                        </li>
                        <li><a href="http://tintuconline.com.vn/the-thao/p0c1047.vnn" class="tt1047">THỂ THAO</a>
                            <ul>
                                <li><a href="http://tintuconline.com.vn/quoc-te/p1047c1048.vnn" title="Quốc tế">Quốc tế</a></li><li><a href="http://tintuconline.com.vn/trong-nuoc/p1047c1161.vnn" title="Trong nước">Trong nước</a></li><li><a href="http://tintuconline.com.vn/hau-truong/p1047c1049.vnn" title="Hậu trường">Hậu trường</a></li>

                            </ul>
                        </li>
                    </ul>
                </div>
                <!--/.nav-collapse -->
            </div>
            <!-- /.navbar-inner -->
        </div>
        <!-- /.navbar -->
    </div>
</div>

    </div></form>