<div class="art-block" id="widget_hoat_dong_quan_trong">
<div class="art-block-tl"></div>
<div class="art-block-tr"></div>
<div class="art-block-bl"></div>
<div class="art-block-br"></div>
<div class="art-block-tc"></div>
<div class="art-block-bc"></div>
<div class="art-block-cl"></div>
<div class="art-block-cr"></div>
<div class="art-block-cc"></div>
<div class="art-block-body">

<div class="art-blockheader">
<div class="l"></div>
<div class="r"></div>
<div class="t"><span id="" class="Head">Hoạt động quan trọng</span></div>
</div>

<div align="right"></div>
<div class="art-blockcontent">
<div class="art-blockcontent-tl"></div>
<div class="art-blockcontent-tr"></div>
<div class="art-blockcontent-bl"></div>
<div class="art-blockcontent-br"></div>
<div class="art-blockcontent-tc"></div>
<div class="art-blockcontent-bc"></div>
<div class="art-blockcontent-cl"></div>
<div class="art-blockcontent-cr"></div>
<div class="art-blockcontent-cc"></div>
<div class="art-blockcontent-body"><!-- block-content -->
<div id=""><!-- Start_Module_605 -->
<?php 
	$lich_ct = Khcn_Api::_()->getDbTable('lich_cong_tac', 'default')->getLichCTByCurrentDate();
	$hoat_dong_qts = null;
	if($lich_ct){
		$hoat_dong_qts = $lich_ct->getNDCTs(array('quan_trong' => 1, 'order' => 'ngay', 'direction' => 'ASC'));
	}
	if(count($hoat_dong_qts) > 0){
?>
	<ul class="list_hoat_dong_quan_trong">
		<?php foreach($hoat_dong_qts as $noi_dung):?>
			<li><strong><?php echo date('d/m/Y', strtotime($noi_dung->ngay))?></strong> - <?php echo $noi_dung->noi_dung?></li>
		<?php endforeach;?>
	</ul>

<?php	
	}else{
?>
	<style type="text/css">
		#widget_hoat_dong_quan_trong {
			display: none;
		}
	</style>
	<?php }?>
<!-- End_Module_605 -->
</div>

<!-- /block-content -->

<div class="cleared"></div>
</div>
</div>

<div align="right"></div>

<div class="cleared"></div>
</div>
</div>