<?php 
	$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
	$this->headMeta()->appendHttpEquiv('Content-Script-Type', 'text/javascript');
	$this->headMeta()->appendHttpEquiv('Content-Script-Type', 'text/css');
	$this->headTitle()->setSeparator(' - ');
	$this->headTitle($this->tenPhong());
	$baseURL = $this->baseUrl();

	echo $this->headMeta();
	echo $this->headTitle();
	$this->headLink()->appendStylesheet($baseURL . '/../application/templates/default/css/ZF/_default/Skins/Skin2/style.css');
	$this->headLink()->appendStylesheet($baseURL . '/../application/templates/default/css/style.css');
	
	$this->headScript()->appendFile($baseURL . '/../application/templates/default/css/ZF/_default/Skins/Skin2/script.js');
	/* Begin jquery */
	$this->headScript()->appendFile($baseURL . '/../application/templates/default/js/jquery/jquery-1.7.1.js');
	$this->headScript()->appendFile($baseURL . '/../application/templates/default/js/jquery/ui/jquery-ui-1.8.9.custom.js');
	$this->headLink()->appendStylesheet($baseURL.'/../application/templates/default/js/jquery/themes/cupertino/jquery-ui-1.8.16.custom.css');
	/* End jquery */
	
	/* Begin simplyscroll */
	$this->headScript()->appendFile($baseURL . '/../application/templates/default/js/jquery/external/jquery-simplyscroll-2.0.4/jquery.simplyscroll.js');
	$this->headLink()->appendStylesheet($baseURL.'/../application/templates/default/js/jquery/external/jquery-simplyscroll-2.0.4/jquery.simplyscroll.css');
	/* End simplyscroll */
	
	/* Staticlogo */
	$this->headScript()->appendFile($baseURL . '/../application/templates/default/js/jquery/external/staticlogo.js');
	echo $this->headLink();
	echo $this->headScript();
?>
<link rel="shortcut icon" href="<?php echo $baseURL . '/images/favicon.ico'?>" type="image/x-icon"/>
	
<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto">
<link rel="stylesheet" href="<?php echo $this->baseUrl() . '/../application/templates/default/css/menu.css'?>">