<div class="art-block" id="widget_lien_ket_trang_mang">
<div class="art-block-tl"></div>
<div class="art-block-tr"></div>
<div class="art-block-bl"></div>
<div class="art-block-br"></div>
<div class="art-block-tc"></div>
<div class="art-block-bc"></div>
<div class="art-block-cl"></div>
<div class="art-block-cr"></div>
<div class="art-block-cc"></div>
<div class="art-block-body">
	<div class="art-blockcontent">
	<div class="art-blockcontent-tl"></div>
	<div class="art-blockcontent-tr"></div>
	<div class="art-blockcontent-bl"></div>
	<div class="art-blockcontent-br"></div>
	<div class="art-blockcontent-tc"></div>
	<div class="art-blockcontent-bc"></div>
	<div class="art-blockcontent-cl"></div>
	<div class="art-blockcontent-cr"></div>
	<div class="art-blockcontent-cc"></div>
	<div class="art-blockcontent-body">
		<!-- block-content -->
		<div class="middle-footer">
			<?php 
				$lienKets = Khcn_Api::_()->getDbTable('lien_ket', 'default')->getLienKets(array('is_sgu' => false));
				if(count($lienKets) > 0){
			?>
					<ul class="List_lien_ket_trang_mang">
					<?php foreach($lienKets as $lien_ket):?>
						<li>
							<a href="<?php echo $lien_ket->getLink()?>" target="_blank" title="<?php echo $lien_ket->getTitle()?>">
								<img src="<?php echo $this->baseUrl() . '/upload/small/images/lien_ket/' . $lien_ket->ten_file?>" />
							</a>
						</li>
					<?php endforeach;?>	
					</ul>
			<?php }else{?>
				<style type="text/css">
					#widget_lien_ket_trang_mang {
						display: none;
					}
				</style>
			<?php } ?>
		</div>
		<!-- /block-content -->
	</div>
	</div>
</div>
</div>