<div class="art-block">
<div class="art-block-tl"></div>
<div class="art-block-tr"></div>
<div class="art-block-bl"></div>
<div class="art-block-br"></div>
<div class="art-block-tc"></div>
<div class="art-block-bc"></div>
<div class="art-block-cl"></div>
<div class="art-block-cr"></div>
<div class="art-block-cc"></div>
<div class="art-block-body">

<div class="art-blockheader">
<div class="l"></div>
<div class="r"></div>
<div class="t"><span id="" class="Head">Đăng nhập</span></div>
</div>
<div align="right"></div>
<div class="art-blockcontent">
<div class="art-blockcontent-tl"></div>
<div class="art-blockcontent-tr"></div>
<div class="art-blockcontent-bl"></div>
<div class="art-blockcontent-br"></div>
<div class="art-blockcontent-tc"></div>
<div class="art-blockcontent-bc"></div>
<div class="art-blockcontent-cl"></div>
<div class="art-blockcontent-cr"></div>
<div class="art-blockcontent-cc"></div>
<div class="art-blockcontent-body"><!-- block-content -->

<div id=""><!-- Start_Module_734 -->
<div class="login">
<?php echo $this->addFormLogin()?>
<?php 
	$viewer = Khcn_Api::_()->getViewer();
    if (!$viewer || !$viewer->getIdentity()) {
?>
<br/>
<div>
<a href="<?php echo $this->url(array('controller' => 'index','action' => 'dang-ky'),null,true);?>" style="font-style: italic;margin-top: 10px;font-size: 14px;">Đăng ký</a>
<a href="<?php echo $this->url(array('controller' => 'index','action' => 'reset-pass'),null,true);?>" style="font-style: italic;float: right;">Quên mật khẩu ?</a>
</div>
<?php }?>
</div>
<!-- End_Module_734 --></div>

<!-- /block-content -->

<div class="cleared"></div>
</div>
</div>

<div align="right"></div>

<div class="cleared"></div>
</div>
</div>