<div class="art-block">
<div class="art-block-tl"></div>
<div class="art-block-tr"></div>
<div class="art-block-bl"></div>
<div class="art-block-br"></div>
<div class="art-block-tc"></div>
<div class="art-block-bc"></div>
<div class="art-block-cl"></div>
<div class="art-block-cr"></div>
<div class="art-block-cc"></div>
<div class="art-block-body">

<div class="art-blockheader">
<div class="l"></div>
<div class="r"></div>
<div class="t"><span id="" class="Head">Thông báo mới</span></div>
</div>

<div align="right"></div>
<div class="art-blockcontent">
<div class="art-blockcontent-tl"></div>
<div class="art-blockcontent-tr"></div>
<div class="art-blockcontent-bl"></div>
<div class="art-blockcontent-br"></div>
<div class="art-blockcontent-tc"></div>
<div class="art-blockcontent-bc"></div>
<div class="art-blockcontent-cl"></div>
<div class="art-blockcontent-cr"></div>
<div class="art-blockcontent-cc"></div>
<div class="art-blockcontent-body"><!-- block-content -->
<script type="text/javascript">
(function($) {
	$(function() { //on DOM ready
		$("#scroller").simplyScroll({
			customClass: 'vert',
			orientation: 'vertical',
			autoMode: 'loop',
            manualMode: 'loop',
			frameRate: 20
		});
	});
})(jQuery);
</script>
<div id=""><!-- Start_Module_605 -->
<?php echo $this->dsThongBaoMoi()?>
<p style="text-align: center;"><a href="<?php echo $this->url(array('controller' => 'index','action' => 'rss'),null,true);?>"><span><img width="36" height="14" alt="" src="<?php echo $this->baseUrl() . '/images/nc-rss.png'?>" /></span></a></p>
<!-- End_Module_605 --></div>

<!-- /block-content -->

<div class="cleared"></div>
</div>
</div>

<div align="right"></div>

<div class="cleared"></div>
</div>
</div>