<p style="text-align: center"><span style="color: rgb(0,0,128)"><span style="font-size: 24px"><span style="font-family: 'Times New Roman'">TRƯỜNG ĐẠI HỌC KHOA HỌC ỨNG DỤNG TÂY BẮC THỤY SĨ HỢP TÁC ĐÀO TẠO </span></span></span></p>

<p style="text-align: center"><span style="color: rgb(0,0,255)"><strong><span style="font-size: 24px"><span style="font-family: 'Times New Roman'">&ldquo;CHUYÊN ĐỀ BỒI DƯỠNG SAU ĐẠI HỌC NGÀNH HÀNH CHÍNH CÔNG&rdquo;</span></span></strong></span><span style="color: rgb(0,0,128)"><span style="font-size: 24px"><span style="font-family: 'Times New Roman'"> </span></span></span></p>

<p style="text-align: center"><span style="color: rgb(0,0,128)"><span style="font-size: 24px"><span style="font-family: 'Times New Roman'">VỚI TRƯỜNG ĐẠI HỌC SÀI GÒN</span></span></span></p>

<div>&nbsp;</div>

<div style="text-align: justify">&nbsp; &nbsp; &nbsp; &nbsp;<span style="font-size: 16px"><span style="font-family: Arial"> &nbsp; Hơn 2 tháng sau ngày kí biên bản ghi nhớ hợp tác giữa Trường Đại học Sài Gòn và Trường Đại học Khoa học Ứng dụng Tây Bắc Thụy Sĩ tại Diễn đàn Giáo dục Đào tạo Việt Nam &ndash; Thụy Sĩ lần thứ 1 vào ngày 12/10/2011, nhân kỉ niệm 40 năm quan hệ ngoại giao Việt Nam &ndash; Thụy sĩ (1971 - 2011). Sáng 28/12/2011, Trường Đại học Khoa học Ứng dụng Tây Bắc Thụy Sĩ đã đến thăm, làm việc và kí kí kết văn bản thoả thuận hợp tác đào tạo &ldquo;Chuyên đề Bồi dưỡng sau Đại học ngành Hành chính công&rdquo; với Trường Đại học Sài Gòn.</span></span></div>

<div style="text-align: justify"><span style="font-size: 16px"><span style="font-family: Arial">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;Tiếp đoàn có PGS.TS. Nguyễn Viết Ngoạn, Bí thư Đảng ủy, Hiệu trưởng Trường; ThS. Lê Văn Việt, Phó Bí thư Đảng ủy, Phó Hiệu trưởng; TS. Lê Hồng Sơn, Trưởng phòng Quan hệ Quốc tế; Bà Nguyễn Thị Thu Hương, Trưởng phòng Hành chính Tổng hợp và Bà Nguyễn Thị Đương, Kế toán trưởng Trường.</span></span></div>

<div style="text-align: justify"><span style="font-size: 16px"><span style="font-family: Arial">Về phía đối tác có GS.TS. Markus Freiburghaus, Thành viên Ban Giám đốc Trường Đại học Khoa học Ứng dụng Tây Bắc Thụy Sĩ; ThS. Đinh Thị Ngọc Liên, giảng viên của trường; TS. Lê Thị Hiệp Thương, Viện trưởng Viện Nghiên cứu và Quản lí Giáo dục Tp. Hồ Chí Minh.</span></span></div>

<div style="text-align: justify"><span style="font-size: 16px"><span style="font-family: Arial">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;Mở đầu buổi làm việc, PGS. TS. Nguyễn Viết Ngoạn, Bí thư Đảng ủy, Hiệu trưởng Trường chào mừng các vị khách đã đến thăm, làm việc tại trường và giới thiệu sơ lược về Trường Đại học Sài Gòn.&nbsp;</span></span></div>

<div style="text-align: justify"><span style="font-size: 16px"><span style="font-family: Arial">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;Phát biểu tại buổi tiếp, GS.TS. Markus Freiburghaus, Thành viên Ban Giám đốc Trường Đại học Khoa học Ứng dụng Tây Bắc Thụy Sĩ đã giới thiệu về trường, các chương trình đào tạo, giảng dạy và nghiên cứu của trường. Ông cũng cho rằng, cần đẩy mạnh quan hệ hợp tác với Trường Đại học Sài Gòn vì hai trường có nhiều điểm tương đồng.</span></span></div>

<div><span style="font-size: 16px"><span style="font-family: Arial">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;Dự kiến khoá đào tạo &ldquo;Chuyên đề Bồi dưỡng sau Đại học ngành Hành chính công&rdquo; sẽ chiêu sinh vào đầu năm 2012.</span></span></div>

<div>&nbsp;</div>

<div><span style="text-align: justify; line-height: 24px; font-family: Arial; font-size: 16px">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <a href="http://sgu.edu.vn/sgu1/index.php?option=com_content&amp;view=article&amp;id=1961:din-an-giao-dc-i-hc-vit-nam-thy-s-&amp;catid=88:newsevent&amp;Itemid=610">Diễn đàn Giáo dục Đại học Việt nam- Thụy Sĩ lần thứ nhất tại Hà Nội (</a></span><a href="http://sgu.edu.vn/sgu1/index.php?option=com_content&amp;view=article&amp;id=1961:din-an-giao-dc-i-hc-vit-nam-thy-s-&amp;catid=88:newsevent&amp;Itemid=610"><span style="font-family: Arial; font-size: 16px">ngày 12/10/2011</span><span style="text-align: justify; line-height: 24px; font-family: Arial; font-size: 16px">)</span></a></div>

<div>&nbsp;</div>

<div><span style="font-size: 16px"><span style="font-family: Arial">&nbsp; &nbsp; &nbsp;</span><strong><span style="font-family: Arial"> &nbsp; &nbsp;&nbsp;Sau đây là một số hình ảnh cuộc họp:</span></strong></span></div>

<div style="text-align: center"><span style="font-size: 16px"><span style="font-family: Arial"><br />

</span></span></div>

<div style="text-align: center"><img alt="" width="550" src="http://paradise.pagevn.vn/upload/news/medium/image001.jpg" /></div>

<div style="text-align: center"><span style="font-size: 16px"><em><span style="font-size: 14px"><span style="font-family: Arial">Toàn cảnh buổi làm việc</span></span></em></span></div>

<div style="text-align: center">&nbsp;</div>

<div style="text-align: center"><em><span style="font-size: 14px"><span style="font-family: Arial"><img alt="" width="550" src="http://paradise.pagevn.vn/upload/news/medium/image003.jpg" /><br />

</span></span></em></div>

<div style="text-align: center"><em><span style="font-size: 14px"><span style="font-family: Arial">PGS.TS Nguyễn Viết Ngoạn, Hiệu trưởng Trường Đại học Sài Gòn, phát biểu trong cuộc họp</span></span></em></div>

<div style="text-align: center"><em><span style="font-size: 14px"><span style="font-family: Arial"><br />

</span></span></em></div>

<div style="text-align: center"><img alt="" width="550" height="376" src="http://paradise.pagevn.vn/upload/news/medium/image005.jpg" /></div>

<div style="text-align: center"><em><span style="font-size: 14px"><span style="font-family: Arial">GS.TS. Markus Freiburghaus, Thành viên Ban Giám đốc Trường Đại học Khoa học Ứng dụng Tây Bắc Thụy Sĩ, t</span></span></em></div>

<div style="text-align: center"><em><span style="font-size: 14px"><span style="font-family: Arial">rao đổi ý kiến với Trường Đại học Sài Gòn</span></span></em></div>

<div style="text-align: center"><em><span style="font-size: 14px"><span style="font-family: Arial"><br />

</span></span></em></div>

<div style="text-align: center"><img alt="" width="550" height="406" src="http://paradise.pagevn.vn/upload/news/medium/image007.jpg" /></div>

<div style="text-align: center"><em><span style="font-size: 14px"><span style="font-family: Arial">Đại diện 2 trường ký kết hợp tác đào tạo</span></span></em></div>

<div style="text-align: center">&nbsp;</div>

<div style="text-align: left">&nbsp;</div>

<div style="text-align: right"><strong><span style="font-size: 16px"><span style="font-family: Arial"><br />

</span></span></strong></div>

<div style="text-align: right"><em><strong><span style="font-size: 16px"><span style="font-family: Arial">Tin: Như Quỳnh</span></span></strong></em></div>

<div style="text-align: right"><em><strong><span style="font-size: 16px"><span style="font-family: Arial">Ảnh: Việt Anh</span></span></strong></em></div>

<p>&nbsp;</p>