<?php $this->titleBlock("Tin Tức - Sự Kiện");?>
<div class="content-news">
<div class="detail">
<div class="title">
<?php echo $this->tin_tuc->getTitle()?>
</div>
<hr color="#06C"/>
<div class="content">
<!-- Begin content news -->
<?php echo $this->tin_tuc->mo_ta_chi_tiet?>
<!-- End content news -->
</div>
<?php if(!empty($this->tin_tuc->file_pdf)):?>
<div class="detail-rule">
	<iframe src="<?php echo 'http://docs.google.com/gview?url=http://' . $_SERVER['HTTP_HOST'] . $this->baseUrl() . '/upload/files/tin_tuc/' . $this->tin_tuc->file_pdf . '&embedded=true'?>" style="width:100%; height:700px;" frameborder="0"></iframe>
</div><br/>
<div class="rules-download">
	<a href="<?php echo $this->baseUrl() . '/upload/files/thong_bao/' . $this->tin_tuc->file_pdf?>" title="<?php echo $this->tin_tuc->getTitle()?>"><img src="<?php echo $this->baseUrl() . '/images/download_button.png'?>" width="100px"/></a>
</div>
<?php endif;?>
</div>

<br/>
<!-- AddThis Button BEGIN -->
<div class="addthis_toolbox addthis_default_style ">
<a class="addthis_button_preferred_1"></a>
<a class="addthis_button_preferred_2"></a>
<a class="addthis_button_preferred_3"></a>
<a class="addthis_button_preferred_4"></a>
<a class="addthis_button_compact"></a>
<a class="addthis_counter addthis_bubble_style"></a>
</div>
<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4ef0b8c73a846dab"></script>
<!-- AddThis Button END -->

<div class="cung_chu_de">
<div>
	<table>
        <tr>
            <td class="header">Các tin khác</td>
            <td>
                <hr style="margin-left: 0px" />
            </td>
        </tr>
    </table>
</div>
<ul>
<?php 
	foreach ($this->cungchude as $tin_tuc)
	{
?>
		<li>
			<img src="<?php echo $this->baseUrl() . '/images/Index.jpg'?>" />
			<b class="title <?php echo $tin_tuc->noi_bat? 'featured' : ''?>"><a href="<?php echo $this->url(array('controller' => 'tin-tuc', 'action' => 'chi-tiet' , 'id' => $tin_tuc['id']),NULL,true)?>"><?php echo $tin_tuc['tieu_de']?></a></b>
			(<?php echo date('d/m/Y', strtotime($tin_tuc['ngay_tao']))?>)
			<?php 
			if($tin_tuc->isNew()){
			?>	
				<img class="new" alt="new" src="<?php echo $this->baseUrl() . '/images/news.gif'?>">
			<?php }?><br/>	 	        
		</li>
<?php 
	}
?>
</ul>
</div>
<div class="view-all"><strong><a href="<?php echo $this->url(array('controller' => 'tin-tuc', 'action' => 'index'),NULL,true)?>">&gt;&gt;&gt; Xem tất cả</a></strong></div>
<!-- End_Module_741 -->
</div>