<?php $this->titleBlock("Nhân sự");?>
<?php if(count($this->nhanSus) > 0):?>
<div class="art-blockcontent list_nhan_su list_items">
	<?php foreach($this->nhanSus as $nhan_su):?>
		<ul class="nhan_su items">
			<li class="photo"><div><img src="<?php echo $nhan_su->getPhotoUrl()?>"></div></li>
			<li class="header"><strong><?php echo $nhan_su->ho_ten?></strong></li>
			<li>
				<ul class="nhan_su_content items_content">
					<li>
						<div class="title">Chức vụ:</div>
						<div class="content"><?php echo $nhan_su->chuc_vu;?></div>
					</li>
					<li>
						<div class="title">Email:</div>
						<div class="content"><?php echo $nhan_su->email;?></div>
					</li>
					<li>
						<div class="title">Website:</div>
						<div class="content"><a href="<?php echo $nhan_su->getWebsiteUrl();?>" target="_blank"><?php echo $nhan_su->website;?></a></div>
					</li>
					<li>
						<div class="title">Số điện thoại:</div>
						<div class="content"><?php echo $nhan_su->so_dien_thoai;?></div>
					</li>
				</ul>
			</li>
		</ul>
	<?php endforeach;?>
</div>
<?php else:?>
	<p><?php echo $this->translate('Đang cập nhật...')?><p>
<?php endif;?>