<?php $this->titleBlock("Sinh hoạt chuyên đề");?>
<script type="text/javascript" src="<?php echo $this->baseUrl()?>/../application/templates/default/js/jquery/external/jquery.fancybox-1.3.4/fancybox/jquery.mousewheel-3.0.4.pack.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl()?>/../application/templates/default/js/jquery/external/jquery.fancybox-1.3.4/fancybox/jquery.fancybox-1.3.4.pack.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl()?>/../application/templates/default/js/jquery/external/jquery.fancybox-1.3.4/fancybox/jquery.fancybox-1.3.4.css" media="screen" />
<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/../application/templates/default/js/jquery/external/jquery.fancybox-1.3.4/style.css" />

<script type="text/javascript">
	$(document).ready(function() {
		$("a[rel=slideshow_group]").fancybox({
			'transitionIn'		: 'none',
			'transitionOut'		: 'none',
			'titlePosition' 	: 'over',
			'cyclic'			: true,
			'titleFormat'		: function(title, currentArray, currentIndex, currentOpts) {
				return '<span id="fancybox-title-over">Image ' + (currentIndex + 1) + ' / ' + currentArray.length + (title.length ? ' &nbsp; ' + title : '') + '</span>';
			}
		});
	});
</script>
<div class="item_detail">
	<div class="info_overview">
		<div class="info_overview_header"><?php echo $this->translate('Thông Tin Chủ Đề')?></div>
		<div class="info_overview_content">
			<div class="item_title">
				<div class="title title_left"><?php echo $this->translate('Chủ đề')?></div>
				<div class="content"><?php echo $this->sinh_hoat_chuyen_de->getTitle()?></div>
			</div>
			<?php if(!empty($this->sinh_hoat_chuyen_de->thoi_gian)):?>
				<div class="thoi_gian">
					<div class="title"><?php echo $this->translate('Thời gian : ')?></div>
					<div class="content"><?php echo date('d/m/Y', strtotime($this->sinh_hoat_chuyen_de->thoi_gian))?></div>
				</div>
			<?php endif;?>
			<?php if(!empty($this->sinh_hoat_chuyen_de->dia_diem)):?>
				<div class="dia_diem">
					<div class="title"><?php echo $this->translate('Địa điểm : ')?></div>
					<div class="content"><?php echo $this->sinh_hoat_chuyen_de->dia_diem?></div>
				</div>
			<?php endif;?>
		</div>
	</div>
	<div class="info_detail border_bottom">
		<div class="info_detail_header"><?php echo $this->translate('Thông Tin Chi Tiết')?></div>
		<div class="content_detail"><?php echo $this->sinh_hoat_chuyen_de->getDescription();?></div>
	</div>
	<?php if(!empty($this->sinh_hoat_chuyen_de->ten_file)):?>
		<div class="files border_bottom">
			<div class="title title_left"><?php echo $this->translate('Download')?></div>
			<div class="content"><a href="<?php echo $this->baseUrl() . '/upload/files/sinh_hoat_chuyen_de/' . $this->sinh_hoat_chuyen_de->ten_file?>"><?php echo $this->sinh_hoat_chuyen_de->ten_file?></a></div>
		</div>
	<?php endif;?>
</div>
<?php if(count($this->hinhAnhs)):?>
<div class="browse_hinh_anh">
	<?php foreach ($this->hinhAnhs as $hinh_anh): ?>
		<div class="item">
			<a rel="slideshow_group" href="<?php echo $hinh_anh->getPhotoUrl()?>"><img alt="" src="<?php echo $hinh_anh->getPhotoUrl()?>" /></a>
		</div>
	<?php endforeach;?>
</div>
<?php endif;?>