<?php
	$url_params = "";
	if (isset($_GET) && count($_GET) > 0) {
		$i = 0;
		foreach ($_GET as $param => $value) {
			if ($i == 0) {
				$url_params .= "?" . $param . "=" . $value;
			} else {
				$url_params .= "&" . $param . "=" . $value;
			}
			$i++;
		}
	}
?>
<?php
if($this->pageCount){
?>
<!-- First page link -->
<?php if (isset($this->previous)){ ?>
   <a class="number" href="<?php echo $this->url(array('page' => $this->first)); ?><?= $url_params ?>">Trang đầu</a>
<?php }?>

<!-- ADD PREVIOUS BUTTON -->
<?php
if(isset($this->previous)){
?>
   <a class="number" href="<?php echo $this->url(array('page' => $this->previous)); ?><?= $url_params ?>">Trang trước</a>
<?php }?>

<!-- SHOW THE AVAILABLE PAGES -->
<?php
foreach($this->pagesInRange as $page){
   if($page != $this->current){
?>
   <a class="number" href="<?php echo $this->url(array('page' => $page)); ?><?= $url_params ?>"><?php echo $page; ?></a>
<?php
   }else{
?>
   <a class="number current" href="#"><?php echo $this->current; ?></a>
<?php
   }
}
?>
<!-- ADD NEXT BUTTON -->
<?php
if(isset($this->next)){
?>
	<a class="number" href="<?php echo $this->url(array('page' => $this->next)); ?><?= $url_params ?>">Trang sau</a>
<?php } ?>

<!-- Last page link -->
<?php if (isset($this->next)){ ?>
    <a class="number" href="<?php echo $this->url(array('page' => $this->last)); ?><?= $url_params ?>">Trang cuối</a>
<?php }?>
<?php
}
?>