<div id="sidebar"><div id="sidebar-wrapper"> <!-- Sidebar with logo and menu -->
	
	<h1 id="sidebar-title"><a href="#">Simpla Admin</a></h1>
  
	<!-- Logo (221px wide) -->
	<a href="#"><img id="logo" src="<?php echo $this->baseUrl() ?>/../application/templates/admin/images/logo_3.png" alt="Simpla Admin logo" /></a>
  
	<!-- Sidebar Profile links -->
	<?php 
		$viewer = Khcn_Api::_()->getViewer();
		$ldnc = date('H:i d/m/Y');
		if($viewer->lan_dang_nhap_cuoi != null)
			$ldnc = date('H:i d/m/Y',strtotime($viewer->lan_dang_nhap_cuoi));
	?>
	<div id="profile-links">
		Xin chào, <a href="#" title="Edit your profile"><?php echo $viewer->ten_hien_thi?></a><br />
		<?php echo $ldnc?><br/>
		<a href="<?php echo $this->url(array(),null,true)?>" title="Sign Out" target="_blank">View site</a> | <a href="<?php echo $this->url(array('controller' => 'dang-nhap','action' => 'logout'),null,true)?>" title="Sign Out">Sign Out</a>
	</div>        
	
	<ul id="main-nav">  <!-- Accordion Menu -->
		
		<li>
			<a id="index-index" parent_id="index-index" href="<?php echo $this->url(array('module' => 'admin','controller' => 'index','action' => 'index'),null,true)?>" class="nav-top-item no-submenu"> <!-- Add the class "no-submenu" to menu items with no sub menu -->
				Trang chủ
			</a>       
		</li>
		<li> 
			<a id="su-diep" href="#" class="nav-top-item"> <!-- Add the class "current" to current menu item -->
				Sứ điệp
			</a>
			<ul>
				<li><a id="su-diep-them" parent_id="su-diep" href="<?php echo $this->url(array('module' => 'admin','controller' => 'su-diep','action' => 'them'),null,true)?>">Thêm sứ điệp</a></li>
				<li><a id="su-diep-index" parent_id="su-diep" href="<?php echo $this->url(array('module' => 'admin','controller' => 'su-diep','action' => 'index'),null,true)?>">Danh sách sứ điệp</a></li>
				<li><a id="loai-su-diep-them" parent_id="su-diep" href="<?php echo $this->url(array('module' => 'admin','controller' => 'loai-su-diep','action' => 'them'),null,true)?>">Thêm loại sứ điệp</a></li>
				<li><a id="loai-su-diep-index" parent_id="su-diep" href="<?php echo $this->url(array('module' => 'admin','controller' => 'loai-su-diep','action' => 'index'),null,true)?>">Danh sách loại sứ điệp</a></li>
			</ul>
		</li>
		<li> 
			<a id="tin-tuc" href="#" class="nav-top-item"> <!-- Add the class "current" to current menu item -->
				Tin tức
			</a>
			<ul>
				<li><a id="tin-tuc-them" parent_id="tin-tuc" href="<?php echo $this->url(array('module' => 'admin','controller' => 'tin-tuc','action' => 'them'),null,true)?>">Thêm tin tức</a></li>
				<li><a id="tin-tuc-index" parent_id="tin-tuc" href="<?php echo $this->url(array('module' => 'admin','controller' => 'tin-tuc','action' => 'index'),null,true)?>">Danh sách tin tức</a></li>
				<li><a id="loai-tin-tuc-them" parent_id="tin-tuc" href="<?php echo $this->url(array('module' => 'admin','controller' => 'loai-tin-tuc','action' => 'them'),null,true)?>">Thêm loại tin tức</a></li>
				<li><a id="loai-tin-tuc-index" parent_id="tin-tuc" href="<?php echo $this->url(array('module' => 'admin','controller' => 'loai-tin-tuc','action' => 'index'),null,true)?>">Danh sách loại tin tức</a></li>
			</ul>
		</li>
		<li> 
			<a id="dgh" href="#" class="nav-top-item"> <!-- Add the class "current" to current menu item -->
				Đức Giáo Hoàng
			</a>
			<ul>
				<li><a id="dgh-them" parent_id="dgh" href="<?php echo $this->url(array('module' => 'admin','controller' => 'dgh','action' => 'them'),null,true)?>">Thêm ĐGH</a></li>
				<li><a id="dgh-index" parent_id="dgh" href="<?php echo $this->url(array('module' => 'admin','controller' => 'dgh','action' => 'index'),null,true)?>">Danh sách ĐGH</a></li>
				<li><a id="loai-dgh-them" parent_id="dgh" href="<?php echo $this->url(array('module' => 'admin','controller' => 'loai-dgh','action' => 'them'),null,true)?>">Thêm loại ĐGH</a></li>
				<li><a id="loai-dgh-index" parent_id="dgh" href="<?php echo $this->url(array('module' => 'admin','controller' => 'loai-dgh','action' => 'index'),null,true)?>">Danh sách loại ĐGH</a></li>
			</ul>
		</li>
		<li> 
			<a id="bai-viet" href="#" class="nav-top-item"> <!-- Add the class "current" to current menu item -->
				Bài viết
			</a>
			<ul>
				<li><a id="bai-viet-them" parent_id="bai-viet" href="<?php echo $this->url(array('module' => 'admin','controller' => 'bai-viet','action' => 'them'),null,true)?>">Thêm bài viết</a></li>
				<li><a id="bai-viet-index" parent_id="bai-viet" href="<?php echo $this->url(array('module' => 'admin','controller' => 'bai-viet','action' => 'index'),null,true)?>">Danh sách bài viết</a></li>
				<li><a id="loai-bai-viet-them" parent_id="bai-viet" href="<?php echo $this->url(array('module' => 'admin','controller' => 'loai-bai-viet','action' => 'them'),null,true)?>">Thêm loại bài viết</a></li>
				<li><a id="loai-bai-viet-index" parent_id="bai-viet" href="<?php echo $this->url(array('module' => 'admin','controller' => 'loai-bai-viet','action' => 'index'),null,true)?>">Danh sách loại bài viết</a></li>
			</ul>
		</li>
		<li> 
			<a id="thong-tin" href="#" class="nav-top-item"> <!-- Add the class "current" to current menu item -->
				Thông tin
			</a>
			<ul>
				<li><a id="thong-tin-them" parent_id="thong-tin" href="<?php echo $this->url(array('module' => 'admin','controller' => 'thong-tin','action' => 'them'),null,true)?>">Thêm thông tin</a></li>
				<li><a id="thong-tin-index" parent_id="thong-tin" href="<?php echo $this->url(array('module' => 'admin','controller' => 'thong-tin','action' => 'index'),null,true)?>">Danh sách thông tin</a></li>
				<li><a id="loai-thong-tin-them" parent_id="thong-tin" href="<?php echo $this->url(array('module' => 'admin','controller' => 'loai-thong-tin','action' => 'them'),null,true)?>">Thêm loại thông tin</a></li>
				<li><a id="loai-thong-tin-index" parent_id="thong-tin" href="<?php echo $this->url(array('module' => 'admin','controller' => 'loai-thong-tin','action' => 'index'),null,true)?>">Danh sách loại thông tin</a></li>
			</ul>
		</li>
		<li> 
			<a id="chien-dich-cau-nguyen" href="#" class="nav-top-item"> <!-- Add the class "current" to current menu item -->
				Chiến dịch cầu nguyện
			</a>
			<ul>
				<li><a id="chien-dich-cau-nguyen-them" parent_id="chien-dich-cau-nguyen" href="<?php echo $this->url(array('module' => 'admin','controller' => 'chien-dich-cau-nguyen','action' => 'them'),null,true)?>">Thêm CDCN</a></li>
				<li><a id="chien-dich-cau-nguyen-index" parent_id="chien-dich-cau-nguyen" href="<?php echo $this->url(array('module' => 'admin','controller' => 'chien-dich-cau-nguyen','action' => 'index'),null,true)?>">Danh sách CDCN</a></li>
			</ul>
		</li>
		<li> 
			<a id="download" href="#" class="nav-top-item"> <!-- Add the class "current" to current menu item -->
				Download
			</a>
			<ul>
				<li><a id="download-them" parent_id="download" href="<?php echo $this->url(array('module' => 'admin','controller' => 'download','action' => 'them'),null,true)?>">Thêm CDCN</a></li>
				<li><a id="download-index" parent_id="download" href="<?php echo $this->url(array('module' => 'admin','controller' => 'download','action' => 'index'),null,true)?>">Danh sách CDCN</a></li>
			</ul>
		</li>
		<li> 
			<a id="bai-giang" href="#" class="nav-top-item"> <!-- Add the class "current" to current menu item -->
				Bài giảng
			</a>
			<ul>
				<li><a id="bai-giang-them" parent_id="bai-giang" href="<?php echo $this->url(array('module' => 'admin','controller' => 'bai-giang','action' => 'them'),null,true)?>">Thêm bài giảng</a></li>
				<li><a id="bai-giang-index" parent_id="bai-giang" href="<?php echo $this->url(array('module' => 'admin','controller' => 'bai-giang','action' => 'index'),null,true)?>">Danh sách bài giảng</a></li>
			</ul>
		</li>		
		<li> 
			<a id="gioi-thieu" href="#" class="nav-top-item"> <!-- Add the class "current" to current menu item -->
				Giới thiệu - Liên hệ
			</a>
			<ul>
				<li><a id="gioi-thieu-index" parent_id="gioi-thieu" href="<?php echo $this->url(array('module' => 'admin','controller' => 'gioi-thieu','action' => 'index'),null,true)?>">Giới thiệu</a></li>
				<li><a id="gioi-thieu-lien-he" parent_id="gioi-thieu" href="<?php echo $this->url(array('module' => 'admin','controller' => 'gioi-thieu','action' => 'lien-he'),null,true)?>">Liên hệ</a></li>
			</ul>
		</li>
		<?php 
			if($viewer->isAdminOnly()):
		?>
		<li>
			<a id="config" href="#" class="nav-top-item">
				Cấu hình
			</a>
			<ul>
				<!--<li><a id="cau-hinh-index" parent_id="config" href="<?php echo $this->url(array('module' => 'admin','controller' => 'cau-hinh','action' => 'index'),null,true)?>">Cấu hình website</a></li>-->
				<li><a id="cau-hinh-create-index" parent_id="config" href="<?php echo $this->url(array('module' => 'admin','controller' => 'cau-hinh','action' => 'create-index'),null,true)?>">Search index</a></li>
			</ul>
		</li>  
		<?php endif;?>
		    
		
	</ul> <!-- End #main-nav -->	
</div></div>
<?php $request = Zend_Controller_Front::getInstance()->getRequest();?>
<?php $controller_action = $request->getControllerName() . '-' . $request->getActionName();?>
<script language="javascript">
	if(document.getElementById('<?php echo $controller_action ?>')){
		document.getElementById('<?php echo $controller_action ?>').className = 'current';
		var parent_id = document.getElementById('<?php echo $controller_action ?>').getAttribute('parent_id');
		document.getElementById(parent_id).className = 'nav-top-item current';
	}
</script>