<?php 
	$this->headLink()->prependStylesheet($this->layout()->staticBaseUrl . '../application/templates/default/js/swiper/css/swiper.min.css');
	$this->headScript()->appendFile($this->layout()->staticBaseUrl . '../application/templates/default/js/swiper/js/swiper.min.js');
	$tinTucNoiBat = Khcn_Api::_()->default()->getTinTucNoiBat();
	$countTinTucNoiBat = count($tinTucNoiBat);
	$slideshow_1 = array_slice($tinTucNoiBat, 0, -2);
	$slideshow_2 = array_slice($tinTucNoiBat, -2, 2);
?>
<style>
	.AboxSlHot {
		color: #0e76bc;
		float: left;
		font-size: 18px;
		font-weight: bold;
		line-height: 24px;
		padding: 5px 0;
		width: 448px;
	}
	.pboxslhot {
		color: #222;
		float: left;
		font-size: 14px;
		line-height: 18px;
		margin-bottom: 10px;
		width: 448px;
	}
	.swiper-container {
        width: 100%;
        height: 100%;
    }
    .swiper-slide {
		width: 448px;
		height: 360px;
		overflow: hidden;
		transform: perspective(2000px);
    }
	.swiper-slide > .fixborder > span > a > img {
		transform: none !important;
	}
	.swiper-slide img {
		width: 448px !important;
		max-height: 252px !important;
	}
</style>
<div class="row">
	<!-- Slideshow -->
	<div class="span61 fixpdr10">
		<!-- Jssor Slider Begin -->
		<!-- You can move inline styles to css file or css block. -->
		<div class="itsimages">
			<!-- Swiper -->
			<div class="swiper-container">
				<div class="swiper-wrapper">
					<?php foreach($slideshow_1 as $key => $data):?>
					<div class="swiper-slide">
						<div class="fixborder">
							<span><a title="<?php echo $data['item']->getTitle()?>" href="<?php echo $data['item']->getHref();?>">
								<img src="<?php echo $data['item']->getPhotoUrl();?>" >
							</a></span>
						</div>
						<a class="AboxSlHot" href="<?php echo $data['item']->getHref();?>" title="<?php echo $data['item']->getTitle()?>"><?php echo Khcn_Api::_()->default()->subPhrase($data['item']->getTitle(), 100);?></a>
						<p class="pboxslhot"><?php echo Khcn_Api::_()->default()->subPhrase($data['item']->getDescription(), 200);?></p>
					</div>
					<?php endforeach;?>
				</div>
				<!-- Add Pagination -->
				<div class="swiper-pagination"></div>
			</div>
			<script>
				var swiper = new Swiper('.swiper-container', {
					pagination: '.swiper-pagination',
					nextButton: '.swiper-button-next',
					prevButton: '.swiper-button-prev',
					paginationClickable: true,
					spaceBetween: 30,
					centeredSlides: true,
					autoplay: 2500,
					autoplayDisableOnInteraction: false
				});
			</script>
		</div>
		<ul class="nav11">
			<?php foreach($slideshow_2 as $key => $data):?>
				<li>
					<span><a title="<?php echo $data['item']->getTitle()?>" href="<?php echo $data['item']->getHref();?>"><img src="<?php echo $data['item']->getPhotoUrl();?>" title="<?php echo $data['item']->getTitle()?>" border="0"></a></span> 
					<div>
						<a href="<?php echo $data['item']->getHref();?>" title="<?php echo $data['item']->getTitle()?>"><?php echo Khcn_Api::_()->default()->subPhrase($data['item']->getTitle(), 60);?></a>
						<p><?php echo Khcn_Api::_()->default()->subPhrase($data['item']->getDescription(), 200);?></p>
					</div>
				</li>
			<?php endforeach;?>
		</ul>
	</div>
	<!-- Tin Nong -->
	<div class="span31 fixleft">
		<div class="newhot newhots">
			<a href="<?php echo $this->url(array('controller' => 'tin-tuc','action' => 'index'),null,true);?>"><span>TIN NÓNG </span></a>
		</div>
		<?php $tinTucs = Khcn_Api::_()->getDbTable('tin_tuc', 'default')->getDanhSachTinTuc();?>
		<ul class="nav1">
			<?php foreach($tinTucs as $data):?>
			<li>
				<span><a title="<?php echo $data->getTitle()?>" href="<?php echo $data->getHref();?>"><img src="<?php echo $data->getPhotoUrl();?>" border="0"></a></span> 
				<div><a href="<?php echo $data->getHref();?>" title="<?php echo $data->getTitle();?>"><?php echo Khcn_Api::_()->default()->subPhrase($data->getTitle(), 80);?></a></div>
			</li>
			<?php endforeach;?>
		</ul>
	</div>
	<!-- SoundCLoud -->
	<div class="span650 views">
		<iframe width="100%" height="300" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/130167411&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe>
	</div>
	<!-- Su Diep -->
	<?php $suDieps = Khcn_Api::_()->getDbTable('su_diep', 'default')->getDanhSachSuDiep(array('limit' => 5));?>
	<?php if(count($suDieps) > 0): ?>
	<div class="span85 boxDSong">
		<div class="lineRow"></div>
		<div class="boxDSongMenu">
			<div>
				<a href="<?php echo $this->url(array('controller' => 'su-diep','action' => 'index'),null,true);?>" title="Sứ Điệp">Sứ Điệp</a>
			</div>
		</div>
		<div class="span85">
			<div class="fixlineRow01">
			</div>
			<div class="row">
				<div class="span47 fixpdt5">
					<div class="fixborder"><span><a title="<?php echo $suDieps[0]->getTitle()?>" href="<?php echo $suDieps[0]->getHref()?>"><img src="<?php echo $suDieps[0]->getPhotoUrl()?>" title="<?php echo $suDieps[0]->getTitle()?>" border="0"></a></span></div>
					<h4 class="fixpdBt7 boxTheGioi"><a href="<?php echo $suDieps[0]->getHref()?>" title="<?php echo $suDieps[0]->getTitle()?>"><?php echo Khcn_Api::_()->default()->subPhrase($suDieps[0]->getTitle(), 100);?></a></h4>
					<p><?php echo Khcn_Api::_()->default()->subPhrase($suDieps[0]->getDescription(), 200);?></p>
				</div>
				<div class="span472 fixleft">
					<ul class="nav17">
						<?php foreach($suDieps as $index => $su_diep):if($index == 0)continue;?>
						<li>
							<span><a title="<?php echo $su_diep->getTitle()?>" href="<?php echo $su_diep->getHref()?>"><img src="<?php echo $su_diep->getPhotoUrl()?>" border="0"></a></span>
							<div><a href="<?php echo $su_diep->getHref()?>"><?php echo Khcn_Api::_()->default()->subPhrase($su_diep->getTitle(), 80);?></a></div>
						</li>
						<?php endforeach;?>
					</ul>
				</div>
			</div>
		</div>
	</div>
	<?php endif;?>
	<!-- Tin Tuc -->
	<?php $loaiTinTucs = Khcn_Api::_()->getDbTable('loai_tin_tuc', 'default')->getParents();?>
	<?php foreach($loaiTinTucs as $key => $loaiTinTuc):?>
	<div class="span471 block_tin_tuc <?php if($key % 2 != 0) echo 'fixleft'; ?>">
		<div class="lineRow"></div>
		<div class="boxThoisu">
			<div>
				<a href="<?php echo $this->url(array('controller' => 'tin-tuc','action' => 'index', 'loai' => $loaiTinTuc->getIdentity()),null,true);?>" title="<?php echo $loaiTinTuc->getTitle()?>"><?php echo $loaiTinTuc->getTitle()?></a>
			</div>
		</div>
		<?php $tinTucs = Khcn_Api::_()->getDbTable('tin_tuc', 'default')->getDanhSachTinTuc(array('listCategoryIds' => $loaiTinTuc->getRecursiveListIDs(), 'limit' => 4));?>
		<?php if(count($tinTucs) > 0): ?>
		<div class="span47 fixtop fixbdt fixmgt5">
			<div class="fixborder"><span><a title="<?php echo $tinTucs[0]->getTitle()?>" href="<?php echo $tinTucs[0]->getHref()?>"><img src="<?php echo $tinTucs[0]->getPhotoUrl()?>" border="0"></a></span></div>
			<h4 class="fixpdBt7"><a href="<?php echo $tinTucs[0]->getHref()?>" title="<?php echo $tinTucs[0]->getTitle()?>"><?php echo Khcn_Api::_()->default()->subPhrase($tinTucs[0]->getTitle(), 80);?></a></h4>
			<p><?php echo Khcn_Api::_()->default()->subPhrase($tinTucs[0]->getDescription(), 200);?></p>
			<ul class="nav14">
				<?php foreach($tinTucs as $index => $tin_tuc):if($index == 0)continue;?>
				<li>
					<span><a title="<?php echo $tin_tuc->getTitle()?>" href="<?php echo $tin_tuc->getHref()?>"><img src="<?php echo $tin_tuc->getPhotoUrl()?>" border="0"></a></span>
					<div><a href="<?php echo $tin_tuc->getHref()?>" title="<?php echo $tin_tuc->getTitle()?>"><?php echo Khcn_Api::_()->default()->subPhrase($tin_tuc->getTitle(), 80);?></a></div>
				</li>
				<?php endforeach;?>
			</ul>
		</div>
		<?php endif;?>
	</div>
	<?php endforeach;?>
</div>
<!-- Chien Dich Cau Nguyen -->
<div class="row">
	<?php $cdcns = Khcn_Api::_()->getDbTable('chien_dich_cau_nguyen', 'default')->getDanhSachCDCN(array('limit' => 5));?>
	<?php if(count($cdcns) > 0): ?>
	<div class="span85 boxDSong">
		<div class="lineRow"></div>
		<div class="boxDSongMenu">
			<div>
				<a href="<?php echo $this->url(array('controller' => 'chien-dich-cau-nguyen','action' => 'index'),null,true);?>" title="Chiến Dịch Cầu Nguyện">Chiến Dịch Cầu Nguyện</a>
			</div>
		</div>
		<div class="span85">
			<div class="fixlineRow01">
			</div>
			<div class="row">
				<div class="span47 fixpdt5">
					<div class="fixborder"><span><a title="<?php echo $cdcns[0]->getTitle()?>" href="<?php echo $cdcns[0]->getHref()?>"><img src="<?php echo $cdcns[0]->getPhotoUrl()?>" title="<?php echo $cdcns[0]->getTitle()?>" border="0"></a></span></div>
					<h4 class="fixpdBt7 boxTheGioi"><a href="<?php echo $cdcns[0]->getHref()?>" title="<?php echo $cdcns[0]->getTitle()?>"><?php echo Khcn_Api::_()->default()->subPhrase($cdcns[0]->getTitle(), 100);?></a></h4>
					<p><?php echo Khcn_Api::_()->default()->subPhrase($cdcns[0]->getDescription(), 200);?></p>
				</div>
				<div class="span472 fixleft">
					<ul class="nav17">
						<?php foreach($cdcns as $index => $cdcn):if($index == 0)continue;?>
						<li>
							<span><a title="<?php echo $cdcn->getTitle()?>" href="<?php echo $cdcn->getHref()?>"><img src="<?php echo $cdcn->getPhotoUrl()?>" border="0"></a></span>
							<div><a href="<?php echo $cdcn->getHref()?>"><?php echo Khcn_Api::_()->default()->subPhrase($cdcn->getTitle(), 80);?></a></div>
						</li>
						<?php endforeach;?>
					</ul>
				</div>
			</div>
		</div>
	</div>
	<?php endif;?>
</div>
<!-- Thong Tin -->
<div class="row">
	<div class="lineRow"></div>
	<?php $loaiThongTins = Khcn_Api::_()->getDbTable('loai_thong_tin', 'default')->getParents();?>
	<?php foreach($loaiThongTins as $key => $loaiThongTin):?>
	<div class="span215 itemsbox">
		<h3 class="fixmgbt5">
			<a href="<?php echo $this->url(array('controller' => 'thong-tin','action' => 'index', 'loai' => $loaiThongTin->getIdentity()),null,true);?>" title="<?php echo $loaiThongTin->getTitle()?>"><?php echo $loaiThongTin->getTitle()?></a>
		</h3>
		<?php $thongTins = Khcn_Api::_()->getDbTable('thong_tin', 'default')->getDanhSachThongTin(array('listCategoryIds' => $loaiThongTin->getRecursiveListIDs(), 'limit' => 5));?>
		<?php if(count($thongTins) > 0): ?>
		<div class="fixborder"><span><a title="<?php echo $thongTins[0]->getTitle()?>" href="<?php echo $thongTins[0]->getHref()?>"><img src="<?php echo $thongTins[0]->getPhotoUrl()?>" ></a></span></div>
		<h4 class="fixpdBt7"><a href="<?php echo $thongTins[0]->getHref()?>" title="<?php echo $thongTins[0]->getTitle()?>"><?php echo $thongTins[0]->getTitle()?></a></h4>
		<ul class="nav18">
			<?php foreach($thongTins as $index => $thong_tin):if($index == 0)continue;?>
			<li>
				<div><a href="<?php echo $thong_tin->getHref()?>" title="<?php echo $thong_tin->getTitle()?>"><?php echo $thong_tin->getTitle()?></a></div>
			</li>
			<?php endforeach;?>
		</ul>
		<?php endif;?>
	</div>
	<?php endforeach;?>
</div>
<!-- Video -->
<div class="row">
	<?php $loaiVideos = Khcn_Api::_()->getDbTable('loai_video', 'default')->fetchAll();?>
	<?php foreach($loaiVideos as $key => $loaiVideo):?>
	<div class="span471 block_video <?php if($key % 2 != 0) echo 'fixleft'; ?>">
		<div class="lineRow"></div>
		<div class="boxThoisu">
			<div>
				<a href="<?php echo $this->url(array('controller' => 'video','action' => 'index', 'loai' => $loaiVideo->getIdentity()),null,true);?>" title="<?php echo $loaiVideo->getTitle()?>"><?php echo $loaiVideo->getTitle()?></a>
			</div>
		</div>
		<?php $videos = Khcn_Api::_()->getDbTable('video', 'default')->getDanhSachVideo(array( 'loai_video_id' => $loaiVideo->getIdentity(), 'limit' => 4));?>
		<?php if(count($videos) > 0): ?>
		<div class="span47 fixtop fixbdt fixmgt5">
			<ul class="nav18">
				<?php foreach($videos as $index => $video):?>
				<li>
					<div><a href="<?php echo $video->getHref()?>" title="<?php echo $video->getTitle()?>"><?php echo $video->getTitle()?></a></div>
				</li>
				<?php endforeach;?>
			</ul>
		</div>
		<?php endif;?>
	</div>
	<?php endforeach;?>
</div>
<div class="row">
	<div class="fixBoxEmtry">
	</div>
</div>