<?php $this->titleBlock("Reset Password");?>
<div class="msg-error">
	<?php echo $this->dfMessage();?>
</div><br/>
<div class="change">
	<?php echo $this->form;?>
</div>
<div class="info" align="center">
	<ul>
		<li><?php echo $this->translate('Thông tin về password mới sẽ được đính kèm trong e-mail đăng ký của tài khoản.')?></li>
		<li><?php echo $this->translate('Bạn nên thay đổi lại password ngay sau khi đăng nhập thành công với password mới này.')?></li>
		<li><?php echo $this->translate('E-mail xác nhận này chỉ có hiệu lực trong vòng 24h kể từ khi gởi yêu cầu.')?></li>
	</ul>
</div>

