<?php
	$baseURL = $this->baseUrl();
?>
<?php echo $this->message()?>
<style type="text/css">
	#global_page_admin-thong-ke-giang-vien .tbl_giangvien_info .title {
		font-weight: bold;
		width: 150px;
	}
	#global_page_admin-thong-ke-giang-vien .tbl_deTais {
		margin-top: 30px;
	}
	#global_page_admin-thong-ke-giang-vien .tbl_deTais .nam{
		font-weight: bold;
		font-size: 11pt;
		text-align: center;
	}
</style>
<div class="content-box"><!-- Start Content Box -->
<div class="content-box-header">

<h3><?php echo $this->giang_vien->getHoTen()?></h3>

<ul class="content-box-tabs">
	<li><a href="#tab1" class="default-tab"><?php echo $this->translate('Hồ sơ NCKH')?></a></li> <!-- href must be unique and match the id of target div -->
	<li><a href="#tab2"><?php echo $this->translate('Thông tin liên lạc')?></a></li>
</ul>

<div class="clear"></div>

</div>
<!-- End .content-box-header -->
<div class="content-box-content">

	<div class="tab-content default-tab" id="tab1">
		<div class="info_giang_vien">
			<fieldset>
			<table class="tbl_giangvien_info" align="center">
				<tbody>
					<tr>
						<td class="title"><?php echo $this->translate('Mã')?></td>
						<td class="content"><?php echo $this->giang_vien->ma?></td>			
					</tr>
					<tr>
						<td class="title"><?php echo $this->translate('Họ & Tên')?></td>
						<td class="content"><?php echo $this->giang_vien->getHoTen()?></td>			
					</tr>
					<tr>
						<td class="title"><?php echo $this->translate('Đơn vị')?></td>
						<td class="content"><?php echo $this->giang_vien->getDonVi()->ten?></td>			
					</tr>
					<tr>
						<td class="title"><?php echo $this->translate('Chức vụ')?></td>
						<td class="content"><?php echo $this->giang_vien->chuc_vu?></td>			
					</tr>
					<tr>
						<td class="title"><?php echo $this->translate('Số lượng đề tài')?></td>
						<td class="content"><?php echo $this->giang_vien->getSoLuongDT()?></td>			
					</tr>
				</tbody>
			</table>
			</fieldset>
		</div>
		
		<div class="tbl_deTais">
			<fieldset>
			<table align="center">
				<thead>
					<tr class="alt-row">
						<th style="width: 5%"><?php echo $this->translate('STT')?></th>
						<th style="width: 10%"><?php echo $this->translate('Mã')?></th>
						<th style="width: 30%" class="ten"><?php echo $this->translate('Tên')?></th>
						<th style="width: 20%" class="center"><?php echo $this->translate('Đơn vị')?></th>
						<th style="width: 20%" class="center"><?php echo $this->translate('Tình trạng')?></th>
						<th style="width: 15%" class="center"><?php echo $this->translate('Chức vụ')?></th>
					</tr>
				</thead>
				<tbody>
					<?php $count_dt = 0;?>
					<?php foreach($this->datas as $nam => $deTais):?>
					<tr>
						<td colspan="6" class="nam"><?php echo $nam?></td>
					</tr>
						<?php foreach($deTais as $de_tai):?>
						<tr>
							<td class="center"><?php echo ++$count_dt?></td>
							<td><?php echo $de_tai->ma?></td>
							<td class="ten"><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'de-tai','action' => 'sua','id' => $de_tai->id),null,true)?>"><?php echo Khcn_Api::_()->subPhrase($de_tai->ten, 200)?></a> </td>
							<td class="center"><?php echo Khcn_Api::_()->subPhrase($de_tai->getDonVi()->ten, 50)?></td>
							<td class="center"><?php echo $this->tinhTrangs[$de_tai->tinh_trang]?></td>
							<td class="center"><?php echo $de_tai->getChucVuByGV($this->giang_vien)?></td>
						</tr>
						<?php endforeach;?>
					<tr>
						<td colspan="6"></td>
					</tr>
					<?php endforeach;?>
				</tbody>	
			</table>
			</fieldset>
		</div>
	</div>

	<div class="tab-content" id="tab2">
		<div class="info_giang_vien">
			<fieldset>
			<table class="tbl_giangvien_info" align="center">
				<tbody>
					<tr>
						<td class="title"><?php echo $this->translate('Mã')?></td>
						<td class="content"><?php echo $this->giang_vien->ma?></td>			
					</tr>
					<tr>
						<td class="title"><?php echo $this->translate('Họ & Tên')?></td>
						<td class="content"><?php echo $this->giang_vien->getHoTen()?></td>			
					</tr>
					<tr>
						<td class="title"><?php echo $this->translate('Đơn vị')?></td>
						<td class="content"><?php echo $this->giang_vien->getDonVi()->ten?></td>			
					</tr>
					<tr>
						<td class="title"><?php echo $this->translate('Chưc vụ')?></td>
						<td class="content"><?php echo $this->giang_vien->chuc_vu?></td>			
					</tr>
					<tr>
						<td class="title"><?php echo $this->translate('Email')?></td>
						<td class="content"><?php echo $this->giang_vien->email?></td>			
					</tr>
					<tr>
						<td class="title"><?php echo $this->translate('Số điện thoại')?></td>
						<td class="content"><?php echo $this->giang_vien->so_dien_thoai?></td>			
					</tr>
				</tbody>
			</table>
			</fieldset>
		</div>
	</div>
</div>
</div> <!-- End .content-box -->