<?php $this->titleBlock("Phổ biến kiến thức");?>
<div class="browse_list">
	<?php 
		if ($this->paginator->getTotalItemCount() > 0){
			foreach ($this->paginator as $tai_lieu)
			{
	?>
		<div class="list_item">
			<div class="item"><a href="<?php echo $this->url(array('controller' => 'tai-lieu', 'action' => 'chi-tiet' , 'id' => $tai_lieu->getIdentity()),NULL,true)?>" class="ten"><?php echo $tai_lieu->getTitle()?></a></div>
		</div>
	<?php 
			}
		}else{
	?>
			<div id="updating">
				<span><?php echo $this->translate('Đang cập nhật...');?></span>
			</div>
	<?php
		}
	?>	
<div class="pagination">
<?php echo $this->paginator?>
</div>
</div>