<?php
	echo $this->doctype();
	$this->title = "Moderator";
	$this->headTitle($this->title);
	$baseURL = $this->baseUrl();
?>
<?php echo $this->message()?>
<div class="content-box-header">

<h3>Danh sách Moderator</h3>
<div class="clear"></div>

</div>
<!-- End .content-box-header -->
<div class="content-box-content">

<div class="tab-content default-tab" id="tab1">
<div class="danh_sach_mods">
<form action="<?php echo $this->url(array('module' => 'admin','controller' => 'mod-manager','action' => 'xoas'),null,true)?>" method="post" name="f2">
<div class="clear"></div>
<table class="tbl_thongbao" align="center">
	<thead>
		<tr class="alt-row">
			<th><?php echo $this->formCheckbox('deletes',null,array('id' => 'check_all','class' => 'check-all'))?></th>
			<th>Moderator</th>
			<th class="center">Họ tên</th>
			<th class="center">Ngày sinh</th>
			<th class="center">Email</th>
			<th class="center">Ngày tạo</th>
			<th class="center">Trạng thái</th>
			<th></th>
		</tr>
	</thead>
	<tfoot>
		<tr>
			<td colspan="9">
			<div class="bulk-actions align-left">
				<?php echo $this->formSubmit('submit','Xóa',array('onclick' => 'if(confirm("Bạn có thật sự muốn xóa không?")==false) return false','class' => 'button'))?>
				<?php echo $this->formButton('add','Thêm',array('onclick' => 'window.location.href="' . $this->url(array('module' => 'admin','controller' => 'mod-manager','action' => 'them'),null,true) . '"','class' => 'button'))?>
			</div>
			<div class="pagination"> 
            	<?php echo $this->paginator?>
			</div>
			</td>
		</tr>
	</tfoot>
	<tbody>
    <?php
    	foreach ($this->paginator as $quan_tri) 
    	{
    ?>
    		<tr>
			<td><?php echo $this->formCheckbox('item[]',$quan_tri['id'],null)?></td>
			<td><?php echo $quan_tri['ten_dang_nhap']?></td>
			<td class="center"><?php echo $quan_tri['ho_ten']?></td>
			<td class="center"><?php echo $quan_tri['ngay_sinh']?></td>
			<td class="center"><?php echo $quan_tri['email']?></td>
			<td class="center"><?php echo $quan_tri['ngay_tao']?></td>
			<td class="center">
				<a href="<?php echo $this->url(array('module' => 'admin','controller' => 'mod-manager','action' => 'cap-nhat-tt','id' => $quan_tri['id'],'status' => $quan_tri['trang_thai']))?>">
				<img src="<?php echo $baseURL . '/../application/templates/admin/images/icons/trangthai_' . $quan_tri['trang_thai'] . '.png'?>"> </a>
			</td>
			<td>				
				<a href="<?php echo $this->url(array('module' => 'admin','controller' => 'mod-manager','action' => 'xoa','id' => $quan_tri['id']),null,true)?>" title="Delete" onclick="if(confirm('Bạn có thật sự muốn xóa không?')==false) return false ">
				<img src="<?php echo $baseURL . '/../application/templates/admin/images/icons/cross.png'?>" alt="Delete">
			</a></td>
		</tr>
    <?php
    	}
    ?>
                              </tbody>
</table>
</form>
</div>
</div>
<!-- End #tab1 --></div>
<!-- End .content-box-content -->