<?php $this->titleBlock("Biểu mẫu - " . $this->loai_bm->getTitle());?>
<?php if((count($this->childs) > 0) || (count($this->lists) > 0)):?>
	<?php if(count($this->childs) > 0):?>
		<ul class="rules">
			<?php foreach ($this->childs as $child):?>
				<li class="child"><a class="Normal" href="<?php echo $this->baseUrl() . '/bieu-mau/danh-sach/loai/' . $child->getIdentity() ?>">|--<img src="<?php echo $this->baseUrl() . '/images/folder.gif'?>" /> <?php echo $child->getTitle() ?></a></li>
			<?php endforeach;?>
		</ul>
	<?php endif;?>
	
	<?php if(count($this->lists) > 0):?>
	<ul class="rules">
		<?php foreach ($this->lists as $bieu_mau):?>
				<li><a class="Normal" href="<?php echo $this->baseUrl() . '/upload/files/bieu_mau/' . $bieu_mau->ten_file ?>">|--<img src="<?php echo $this->baseUrl() . '/images/folder2.gif'?>" /> <?php echo $bieu_mau->getTitle() ?></a></li>
		<?php endforeach; ?>
	</ul>
	<?php endif;?>
<?php else:?>
		<p>Đang cập nhật ...</p>
<?php endif;?>