<?php
	echo $this->doctype();
	$this->title = "Người dùng";
	$this->headTitle($this->title);
	$baseURL = $this->baseUrl();
?>

<?php echo $this->message()?>
<div class="content-box"><!-- Start Content Box -->

<div class="content-box-header">

<h3>Sửa người dùng</h3>

<div class="clear"></div>
</div>
<!-- End .content-box-header -->

<div class="content-box-content">

<div class="tab-content default-tab" id="tab1"><!-- This is the target div. id must match the href of this div's tab -->
<?php echo $this->form->render($this);?>
<script type="text/javascript">
function optionGV(is_giang_vien){
	var display = 'none';
	if(is_giang_vien == 1){
		display = '';
	}
	$("#giang_vien_id-wrapper").css('display', display);
	$("#don_vi_id-wrapper").css('display', display);
}

$(document).ready(function(){ 
	<?php if(isset($this->giang_vien) && !empty($this->giang_vien)):?>
		optionGV(1);
	<?php else:?>
		optionGV(0);
	<?php endif;?>
	$("#is_giang_vien").click(function(){
		if($("#is_giang_vien").is(':checked')){
			optionGV(1);
		}else{
			optionGV(0);
		}
	});
	
	$("#don_vi_id").change(function(){
		var id = $('#don_vi_id').val();
		$.ajax({
				 type: "POST",
				 url: "<?php echo $this->url(array('module' => 'admin','controller' => 'giang-vien','action' => 'load'))?>", 
				 data: {'id' : id},
				 success: function(response){
					 $('#giang_vien_id').empty().append(response);
			     }
			});
	});
});
</script>
<script type="text/javascript">
$(function() {
	$( "#ngay_sinh" ).datepicker({
		showOn: "button",
		changeYear: true,
		changeMonth: true,
		buttonImage: "<?php echo $baseURL . '/images/calendar.gif'?>",
		buttonImageOnly: true,
		altFormat: 'dd-mm-yy',
		dateFormat: 'dd-mm-yy',
		yearRange : '1900:2000'
	});
});
</script>
</div>
<!-- End #tab1 -->
<!--<div class="tab-content" id="tab2"></div>-->
</div>
<!-- End .content-box-content --></div>
<!-- End .content-box -->