<?php
	echo $this->doctype()->__toString();  
?>
<html>
<head>
	<?php
    $counter = (int) $this->layout()->counter;
    $staticBaseUrl = $this->layout()->staticBaseUrl;
    
    $request = Zend_Controller_Front::getInstance()->getRequest();
    $this->headTitle()
      ->setSeparator(' - ');
    $pageTitleKey = 'pagetitle-' . $request->getModuleName() . '-' . $request->getActionName()
        . '-' . $request->getControllerName();
    $pageTitle = $this->translate($pageTitleKey);
  
    // Make description and keywords
    $description = '';
    $keywords = '';
    
    $description .= ' ' .$this->layout()->siteinfo['description'];
    $keywords = $this->layout()->siteinfo['keywords'];
    
    $this->headMeta()->appendName('description', trim($description));
    $this->headMeta()->appendName('keywords', trim($keywords));

    // Get body identity
    if( isset($this->layout()->siteinfo['identity']) ) {
      $identity = $this->layout()->siteinfo['identity'];
    } else {
      $identity = $request->getModuleName() . '-' .
          $request->getControllerName() . '-' .
          $request->getActionName();
    }
	
	$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
	$this->headMeta()->appendHttpEquiv('Content-Script-Type', 'text/javascript');
	$this->headMeta()->appendHttpEquiv('Content-Script-Type', 'text/css');
	$this->headTitle()->setSeparator(' - ');
	$this->headTitle($this->tenPhong());
	$baseURL = $this->baseUrl();

	echo $this->headMeta();
	echo $this->headTitle();
	$this->headLink()->prependStylesheet($baseURL.'/../application/templates/default/js/jquery/external/jquery-simplyscroll-2.0.4/jquery.simplyscroll.css');
	$this->headLink()->prependStylesheet($baseURL.'/../application/templates/default/js/jquery/themes/cupertino/jquery-ui-1.8.16.custom.css');
	//$this->headLink()->prependStylesheet($baseURL . '/../application/templates/default/css/style.css');	
	echo $this->headLink()->toString()."\n";
	
	
	$this->headScript()->prependFile($baseURL . '/../application/templates/default/js/jquery/ui/jquery-ui-1.8.9.custom.js');
	$this->headScript()->prependFile($baseURL . '/../application/templates/default/js/jquery/external/jquery-simplyscroll-2.0.4/jquery.simplyscroll.js');
	$this->headScript()->prependFile($baseURL . '/../application/templates/default/js/jquery/jquery-1.7.1.js');	
	echo $this->headScript()->toString()."\n";
  ?>
  
  <meta id="keywords" name="keywords" content="tin tức online, tin tức nhanh, tin nóng, thế giới 24h, kinh doanh, pháp luật, khoa học, công nghệ." />
  <meta id="description" name="description" content="Tin tức nóng cập nhật liên tục, tin Việt Nam, Thế giới, tin xã hội, kinh doanh, pháp luật, khoa học, công nghệ, đời sống, văn hóa, giáo dục, gia đình" />
  <meta name="google-site-verification" content="QprtiYlW0XQZ-hwosf_TNaFNFfUuBWbGfxotNl_0DRo" />
  <meta name="page-topic" content="Tin tức Online" />
  <meta name="copyright" content="TintucOnline.com.vn" />
  <meta http-equiv="audience" content="General" />
  <meta name="resource-type" content="Document" />
  <meta name="distribution" content="Global" />
  <meta name="revisit-after" content="1 days" />
  <meta name="robots" content="index,follow" />
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta property="article:publisher" content="https://www.facebook.com/tintuconlinevnn" />
  <meta property="article:author" content="https://www.facebook.com/tintuconlinevnn" />
  <link rel="shortcut icon" href="http://tintuconline.com.vn/Images/favicon.gif" type="image/x-icon" />
  <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() . '/../application/templates/default/css/bootstrap.css'?>" />
  <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() . '/../application/templates/default/css/extension.css'?>" />
  <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() . '/../application/templates/default/css/Fix.css'?>" />
  <link rel="stylesheet" href="<?php echo $this->baseUrl() . '/../application/templates/default/css/SlideImage.css'?>" type="text/css" media="screen" />
  <link rel="stylesheet" href="<?php echo $this->baseUrl() . '/../application/templates/default/css/flexslider.css'?>" type="text/css" media="screen" />
  <link href="<?php echo $this->baseUrl() . '/../application/templates/default/css/pollEditor.css'?>" rel="stylesheet" type="text/css" />
  <link href="<?php echo $this->baseUrl() . '/../application/templates/default/css/css.css'?>" rel="stylesheet" type="text/css" />
  
  
    <script src="http://tintuconline.com.vn/Scripts/jquery.simplemodal.js" type="text/javascript"></script>
    <script src="http://tintuconline.com.vn/Scripts/jssor.slider.js" type="text/javascript"></script>
    <script src="http://tintuconline.com.vn/Scripts/jssor.js" type="text/javascript"></script>
    <script src="http://tintuconline.com.vn/Scripts/jquery.flexslider.js" type="text/javascript"></script>
    <script src='http://tintuconline.com.vn/Scripts/jquery-latest.js' type='text/javascript'></script>
    <script src="http://tintuconline.com.vn/Scripts/Common.v2.js" type="text/javascript"></script>
    <script src="http://tintuconline.com.vn/Scripts/clip-media.js" type="text/javascript"></script>
    <script src="http://tintuconline.com.vn/Scripts/swfobject.js" type="text/javascript"></script>
    <!-- <script src="http://tintuconline.com.vn/Scripts/npm.js" type="text/javascript"></script>-->
    <script type="text/javascript">
        function vmcLoadScript(selector, scriptUrl) {
            $(selector).writeCapture().html("<script type='text/javascript' language='javascript' src='" + scriptUrl + "'><\/script>");
        }

        function LoadImage(id, src) {
            id.src = src;
            id.onerror = null;
        };
    </script>
    <link type="text/css" rel="stylesheet" href="../public/upload/2sao.vn/Styles/Widget.css">
	<script type="text/javascript" src="http://2sao.vn/Services/JSon.ashx?callBack=ClipRenderBoxTTOL&amp;top=3"></script>
	<script src="http://plugins.longtailvideo.com/5/ova/ova-jw.js"></script>
	<script type="text/javascript" src="file://rtax.criteo.com/delivery/rta/rta.js?netId=3760&amp;cookieName=crtg_rta&amp;rnd=80895735299&amp;varName=crtg_content" async=""></script>
	<link href="index.html" rel="canonical" />

	<link rel="shortcut icon" href="<?php echo $baseURL . '/images/favicon.ico'?>" type="image/x-icon"/>
	
	<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto">
	<link rel="stylesheet" href="<?php echo $this->baseUrl() . '/../application/templates/default/css/menu.css'?>">
</head>
<body id="global_page_<?php echo $identity ?>">
	<div id="global_header">
		<!-- Begin header -->
		<?php echo $this->render('includes/header.phtml') ?>
		<!-- End header -->
	</div>
	
	<div id='global_wrapper'>
		<div id='global_content'>
			<div class="container">
				<div class="row">
					<div class="span85">
						<?php echo $this->layout()->content ?>
					</div>
					<div class="span4 fixleft">
						<?php echo $this->render('includes/right-widget.phtml') ?>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div id="global_footer">
		<?php echo $this->render('includes/footer.phtml') ?>
	</div>
</body>
</html>