<?php
	echo $this->doctype();
	$this->title = "Cấu hình";
	$this->headTitle($this->title);
	$baseURL = $this->baseUrl();
?>
<?php echo $this->message()?>
<div class="content-box"><!-- Start Content Box -->

<div class="content-box-header">

<h3>Cấu hình</h3>
</div>
<!-- End .content-box-header -->

<div class="content-box-content">

<div class="tab-content default-tab" id="tab1"><!-- This is the target div. id must match the href of this div's tab -->
<?php echo $this->form?>
<script type="text/javascript" language="javascript">				
	CKEDITOR.replace( 'cesti_info', {'skin' : 'v2','height' : '500px'} );				
</script>
</div>

<!-- End #tab1 --></div>
<!-- End .content-box-content --></div>
<!-- End .content-box -->