<?php
/**
 * SocialEngine
 *
 * @category   Application_Core
 * @package    Core
 * @copyright  Copyright 2006-2010 Webligo Developments
 * @license    http://www.socialengine.net/license/
 * @version    $Id: settings.tpl 7244 2010-09-01 01:49:53Z john $
 * @author     John
 */
?>
<?php
	$this->title = "Mail Settings";
	$this->headTitle($this->title);
	$baseURL = $this->baseUrl();
?>
<?php echo $this->message()?>
<div class="content-box"><!-- Start Content Box -->

<div class="content-box-header">

<h3>Mail Settings</h3>

<div class="clear"></div>
</div>
<!-- End .content-box-header -->

<div class="content-box-content">

<div class="tab-content default-tab" id="tab1"><!-- This is the target div. id must match the href of this div's tab -->
<?php echo $this->form?>
</div>
<!-- End #tab1 -->
<!--<div class="tab-content" id="tab2"></div>-->
</div>
<!-- End .content-box-content --></div>
<!-- End .content-box -->

<script type="text/javascript">
  $(document).ready(function(){ 
	
    var smtp = $('#mail_smtp_server-wrapper, \
                          #mail_smtp_port-wrapper, \
                          #mail_smtp_authentication-wrapper, \
                          #mail_smtp_username-wrapper, \
                          #mail_smtp_password-wrapper, \
                          #mail_smtp_ssl-wrapper');

    var auth = $('#mail_smtp_username-wrapper, #mail_smtp_password-wrapper');

    if( ($('input[id=mail_smtp-1]:checked').length) ){
      smtp.css('display','');
    } else {
      smtp.css('display','none');
    }

    $('input[name=mail_smtp]').change(function(){
      if( !this.checked ) return;
      if( this.value == 1 ){
        smtp.css('display','');
        if( ($('input[id=mail_smtp_authentication-1]:checked').length) ){
          auth.css('display','');
        } else {
          auth.css('display','none');
        }
      } else {
        smtp.css('display','none');
      }
    });

    if(  ($('input[id=mail_smtp-1]:checked').length) &&
      ($('input[id=mail_smtp_authentication-1]:checked').length) ){
      auth.css('display','');
    } else {
      auth.css('display','none');
    }

    $('input[name=mail_smtp_authentication]').change(function(){
      if( !this.checked ) return;
      if( this.value == 1 ){
        auth.css('display','');
      } else {
        auth.css('display','none');
      }
    });

  });

</script>
