<?php $this->titleBlock($this->loai_hs->getTitle());?>
<?php if(count($this->danhSachHs) > 0 ){?>
<ul class="rules list_folder_file">
	<?php 
		foreach ($this->danhSachHs as $ho_so)
		{
	?>
			<li><a class="Normal file" href="<?php echo $this->baseUrl() . '/upload/files/ho_so/' . $ho_so->ten_file ?>">|--<img src="<?php echo $this->baseUrl() . '/images/folder2.gif'?>" /> <?php echo $ho_so->getTitle() ?></a></li>
	<?php 
		}
	?>
</ul>
<?php
	}else{
?>
		<p>Đang cập nhật ...</p>
<?php }?>