<?php
	echo $this->doctype();
	$this->title = "ĐGH";
	$this->headTitle($this->title);
	$baseURL = $this->baseUrl();
?>
<?php echo $this->message()?>
<div class="content-box-header">

<h3>Danh sách ĐGH</h3>
<div class="clear"></div>

</div>
<!-- End .content-box-header -->
<?php echo $this->form;?>
<div class="content-box-content">

<div class="tab-content default-tab" id="tab1">
<div class="danh_sach_hoi_thao">
<form action="<?php echo $this->url(array('module' => 'admin','controller' => 'dgh','action' => 'xoas'),null,true)?>" method="post" name="f2">
<div class="clear"></div>
<table class="tbl_bomon" align="center">
	<thead>
		<tr class="alt-row">
			<th><?php echo $this->formCheckbox('deletes',null,array('id' => 'check_all','class' => 'check-all'))?></th>
			<th class="chu_de" style="width: 35%;">Tên</th>
			<th class="center">Loại</th>
			<th></th>
		</tr>
	</thead>
	<tfoot>
		<tr>
			<td colspan="9">
			<div class="bulk-actions align-left">
				<?php echo $this->formSubmit('submit','Xóa',array('onclick' => 'if(confirm("Bạn có thật sự muốn xóa không?")==false) return false','class' => 'button'))?>
				<?php echo $this->formButton('add','Thêm',array('onclick' => 'window.location.href="' . $this->url(array('module' => 'admin','controller' => 'dgh','action' => 'them'),null,true) . '"','class' => 'button'))?>
			</div>
			<div class="pagination"> 
            	<?php echo $this->paginator?>
			</div>
			</td>
		</tr>
	</tfoot>
	<tbody>
    <?php
    	foreach ($this->paginator as $dgh) 
    	{
    ?>
    		<tr>
			<td><?php echo $this->formCheckbox('item[]',$dgh->getIdentity(),null)?></td>
			<td><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'dgh','action' => 'sua','id' => $dgh->getIdentity()),null,true)?>" title="<?php echo $dgh->getTitle()?>"><?php echo $dgh->getTitle()?></a></td>		
			<td class="center"><?php echo $dgh->getLoai()->getTitle();?></td>
			<td>
				<a href="<?php echo $this->url(array('module' => 'admin','controller' => 'dgh','action' => 'sua','id' => $dgh->getIdentity()),null,true)?>" title="Sửa"> 
				<img src="<?php echo $baseURL . '/../application/templates/admin/images/icons/pencil.png'?>" alt="Edit"> </a>
				<a href="<?php echo $this->url(array('module' => 'admin','controller' => 'dgh','action' => 'xoa','id' => $dgh->getIdentity()),null,true)?>" title="Xóa" onclick="if(confirm('Bạn có thật sự muốn xóa không?')==false) return false ">
				<img src="<?php echo $baseURL . '/../application/templates/admin/images/icons/cross.png'?>" alt="Delete">
			</a></td>
		</tr>
    <?php
    	}
    ?>
                              </tbody>
</table>
</form>
</div>
</div>
<!-- End #tab1 --></div>
<!-- End .content-box-content -->