<?php $this->titleBlock("Qui định");?>
<div class="detail-rule">
	<iframe src="<?php echo 'http://docs.google.com/gview?url=http://' . $_SERVER['HTTP_HOST'] . $this->baseUrl() . '/upload/files/qui_dinh/' . $this->qui_dinh['ten_file'] . '&embedded=true'?>" style="width:100%; height:700px;" frameborder="0"></iframe>
</div><br/>
<div class="rules-download">
	<a href="<?php echo $this->baseUrl() . '/upload/files/qui_dinh/' . $this->qui_dinh['ten_file']?>" title="<?php echo $this->qui_dinh['ten']?>"><img src="<?php echo $this->baseUrl() . '/images/download_button.png'?>" width="100px"/></a>
</div>