<?php $this->titleBlock("Lịch thi - " . $this->he_cao_hoc->getTitle());?>
<div class="list-announcement">
<table class="blog" cellpadding="0" cellspacing="0">
	<tbody>	
		<?php 
		if ($this->paginator->getTotalItemCount() > 0){
			foreach ($this->paginator as $lich_thi)
			{
		?>
				<tr>
					<td valign="top">
					<div class="announcements">
					<span class="tieude">
						<strong><?php echo date('d/m/Y', strtotime($lich_thi->ngay_tao))?></strong>
						-
						<a href="<?php echo $this->url(array('controller' => 'lich-thi', 'action' => 'chi-tiet' , 'id' => $lich_thi->getIdentity()),NULL,true)?>"><?php echo $lich_thi->getTitle()?></a>
						<?php 
						if($lich_thi->isNew()){
						?>	
							<img class="new" alt="new" src="<?php echo $this->baseUrl() . '/images/news.gif'?>">
						<?php }?>
					</span>						
					<a class="chitiet" href="<?php echo $this->url(array('controller' => 'lich-thi', 'action' => 'chi-tiet' , 'id' => $lich_thi->getIdentity()),NULL,true)?>">Chi tiết...</a>
					<div class="cleared"></div>
					</div>
					<span class="article_separator">&nbsp;</span></td>
				</tr>
		<?php 
			}
		}else{?>
			<p>Đang cập nhật ...</p>
		<?php
		}
		?>		
	</tbody>
</table>
<div class="pagination">
<?php echo $this->paginator?>
</div>
</div>